# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "AuditAction",
    "DecoyType",
)

import enum
import typing

if typing.TYPE_CHECKING:
    import collections.abc


class AuditAction(enum.StrEnum):
    LOGIN = "login"
    BAN_CREATED = "ban_created"
    BAN_REVOKED = "ban_revoked"
    DECOY_REVOKED = "decoy_revoked"
    SETTINGS_CHANGED = "settings_changed"


class DecoyType(enum.StrEnum):
    TEXT = "text"
    BINARY = "binary"
    TRAP = "trap"
