# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "AuditAction",
    "EventKind",
    "PathCategory",
    "RouterGroup",
)

import enum
import typing

if typing.TYPE_CHECKING:
    import collections.abc


class AuditAction(enum.StrEnum):
    LOGIN = "login"
    BAN_CREATED = "ban_created"
    BAN_REVOKED = "ban_revoked"
    RULE_CREATED = "rule_created"
    RULE_CHANGED = "rule_changed"
    RULE_REMOVED = "rule_removed"


class EventKind(enum.StrEnum):
    HIT = "hit"
    LOGIN_ATTEMPT = "login_attempt"
    INSTALL_ATTEMPT = "install_attempt"


class PathCategory(enum.StrEnum):
    HOMEPAGE = "homepage"
    CRAWLERS = "crawlers"
    SECRETS = "secrets"
    BACKUPS = "backups"
    DEBUG = "debug"
    EXPLOITS = "exploits"
    WORDPRESS = "wordpress"
    WEBSHELLS = "webshells"
    LOGINS = "logins"
    APIS = "apis"
    OTHER = "other"


class RouterGroup(enum.StrEnum):
    EXHIBIT = "exhibit"
    SYSTEM = "system"
    HONEYPOT = "honeypot"
    INGEST = "ingest"
    ADMIN = "admin"
