# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "AdminAuditLog",
    "CanaryToken",
    "CredentialStuffingAttempt",
    "Decoy",
    "DecoyBinaryPath",
    "DecoyConfig",
    "DecoyLockout",
    "DecoyPasswordAttempt",
    "DecoyRevocation",
    "DecoyTextContent",
    "DecoyView",
    "InstallAttempt",
    "IpActivity",
    "IpBan",
    "IpLocation",
    "IpRequestPath",
    "OauthState",
    "SchemaMigration",
    "Session",
    "TelemetryHit",
    "User",
)

import datetime
import pydantic
import typing
import uuid

if typing.TYPE_CHECKING:
    import collections.abc

from . import enums


class AdminAuditLog(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    user_id: int
    action: enums.AuditAction
    target_ip: str | None
    details: str
    logged_at: datetime.datetime


class CanaryToken(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    token: str
    path: str
    ip_address: str
    issued_at: datetime.datetime


class CredentialStuffingAttempt(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    endpoint_path: str
    username: str
    password: str
    was_fake_success: bool
    attempted_at: datetime.datetime
    canary_id: int | None
    install_id: int | None


class Decoy(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    type: enums.DecoyType
    slug: str
    added: datetime.datetime
    added_by_ip: str
    added_by_user_id: int | None


class DecoyBinaryPath(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    decoy_id: int
    file_path: str


class DecoyConfig(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    decoy_id: int
    expires_at: datetime.datetime | None
    password_hash: str | None
    one_time_view: bool


class DecoyLockout(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    decoy_id: int
    ip_address: str
    added: datetime.datetime
    expires: datetime.datetime


class DecoyPasswordAttempt(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    decoy_id: int
    ip_address: str
    successful: bool
    attempted_at: datetime.datetime


class DecoyRevocation(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    decoy_id: int
    revoked_at: datetime.datetime
    revoked_by_user_id: int


class DecoyTextContent(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    decoy_id: int
    content: str


class DecoyView(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    decoy_id: int
    ip_address: str
    viewed_at: datetime.datetime


class InstallAttempt(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    path: str
    site_title: str
    username: str
    email: str
    password: str
    password_generated: bool
    attempted_at: datetime.datetime


class IpActivity(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    ip_address: str
    requests: int
    distinct_paths: int
    login_attempts: int
    first_seen_at: datetime.datetime | None
    last_seen_at: datetime.datetime | None
    install_attempts: int
    banned_requests: int


class IpBan(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    added: datetime.datetime
    expires: datetime.datetime | None
    reason: str | None
    added_by_user_id: int
    revoked_at: datetime.datetime | None
    revoked_by_user_id: int | None
    revocation_reason: str | None


class IpLocation(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    ip_address: str
    country_code: str | None
    city: str | None
    latitude: float | None
    longitude: float | None
    asn: int | None
    as_organisation: str | None
    source: str
    located_at: datetime.datetime


class IpRequestPath(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    ip_address: str
    path_md5: uuid.UUID


class OauthState(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    state: str
    code_verifier: str
    created: datetime.datetime
    expires: datetime.datetime


class SchemaMigration(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    version: int
    name: str
    sha256: str
    applied_at: datetime.datetime


class Session(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    user_id: int
    token_hash: str
    created: datetime.datetime
    expires: datetime.datetime
    last_used: datetime.datetime


class TelemetryHit(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    method: str
    path: str
    query: str | None
    router_group: enums.RouterGroup
    user_agent: str | None
    headers: str
    body: memoryview | None
    body_size: int | None
    status_code: int
    occurred_at: datetime.datetime
    banned: bool


class User(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    google_sub: str
    email: str
    name: str
    created: datetime.datetime
    last_login: datetime.datetime
