# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: queries.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "BusiestAddressesRow",
    "CountCategoriesSinceRow",
    "CountRequestsPerHourSinceRow",
    "CreateCredentialStuffingAttemptRow",
    "GetActiveIpBanRow",
    "GetHitRow",
    "GetHitsByIdsRow",
    "GetInstallAttemptsByIdsRow",
    "GetIpActivityRow",
    "GetLoginAttemptsByIdsRow",
    "GetObservationSpanRow",
    "GetPatternTotalsRow",
    "GetVisitorFactsRow",
    "ListActiveRulesRow",
    "ListAppliedMigrationsRow",
    "ListAuditLogRow",
    "ListIpBansRow",
    "ListIpEventsRow",
    "ListMapPlacesRow",
    "ListRecentEventsRow",
    "ListRulesRow",
    "ListToolkitsRow",
    "LongestSeenAddressesRow",
    "QueryResults",
    "TopCountriesRow",
    "TopNetworksRow",
    "TopPasswordsSinceRow",
    "TopPathsSinceRow",
    "TopUserAgentsSinceRow",
    "TopUsernamesSinceRow",
    "UseSessionRow",
    "busiest_addresses",
    "categorise_path",
    "count_categories_since",
    "count_install_logins",
    "count_login_attempts_since",
    "count_requests_per_hour_since",
    "count_requests_since",
    "create_audit_log_entry",
    "create_canary_token",
    "create_credential_stuffing_attempt",
    "create_install_attempt",
    "create_ip_ban",
    "create_ip_location",
    "create_o_auth_state",
    "create_public_schema",
    "create_rule",
    "create_session",
    "create_telemetry_hit",
    "delete_session",
    "drop_public_schema",
    "get_active_ip_ban",
    "get_hit",
    "get_hits_by_ids",
    "get_install_attempts_by_ids",
    "get_ip_activity",
    "get_ip_locations",
    "get_login_attempts_by_ids",
    "get_observation_span",
    "get_pattern_totals",
    "get_visitor_facts",
    "is_ip_banned",
    "list_active_rules",
    "list_applied_migrations",
    "list_audit_log",
    "list_install_login_ids",
    "list_ip_bans",
    "list_ip_events",
    "list_map_places",
    "list_paths_of",
    "list_recent_events",
    "list_rules",
    "list_toolkits",
    "list_unlocated_addresses",
    "longest_seen_addresses",
    "prune_o_auth_states",
    "prune_sessions",
    "record_migration",
    "remove_rule",
    "revoke_ip_ban",
    "seed_hits",
    "seed_login_attempts",
    "set_rule_position",
    "take_o_auth_state",
    "top_countries",
    "top_networks",
    "top_passwords_since",
    "top_paths_since",
    "top_user_agents_since",
    "top_usernames_since",
    "update_rule",
    "upsert_user",
    "use_session",
)

import collections.abc
import datetime
import operator
import pydantic
import typing

if typing.TYPE_CHECKING:
    import psycopg
    import psycopg.rows

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = psycopg.AsyncConnection[psycopg.rows.TupleRow]

from . import enums
from . import models


class CreateCredentialStuffingAttemptRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    was_fake_success: bool
    known_account: bool


class UseSessionRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    email: str
    name: str


class ListActiveRulesRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    method: str | None
    path_pattern: str | None
    condition: str
    status_code: int
    content_type: str
    headers: str
    body: str
    delay_ms: int


class ListRulesRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    position: int
    method: str | None
    path_pattern: str | None
    condition: str
    status_code: int
    content_type: str
    headers: str
    body: str
    delay_ms: int
    expires: datetime.datetime | None
    note: str | None
    updated: datetime.datetime
    hits: int


class GetVisitorFactsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    country_code: str | None
    city: str | None
    asn: int | None
    as_organisation: str | None
    requests: int | None
    first_seen_at: datetime.datetime | None
    logins: int
    has_canary: bool
    banned_before: bool


class ListAuditLogRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    logged_at: datetime.datetime
    email: str
    action: enums.AuditAction
    target_ip: str | None
    details: str


class GetActiveIpBanRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    added: datetime.datetime
    expires: datetime.datetime | None


class ListIpBansRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    added: datetime.datetime
    expires: datetime.datetime | None
    reason: str | None
    added_by: str
    revoked_at: datetime.datetime | None
    revoked_by: str | None
    revocation_reason: str | None
    active: bool | None


class ListRecentEventsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    kind: enums.EventKind
    id_: int
    ip_address: str
    occurred_at: datetime.datetime


class ListIpEventsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    kind: enums.EventKind
    id_: int
    ip_address: str
    occurred_at: datetime.datetime


class GetHitsByIdsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    occurred_at: datetime.datetime
    method: str
    path: str
    query: str | None
    status_code: int
    user_agent: str | None
    body_preview: memoryview
    body_size: int | None
    category: enums.PathCategory
    banned: bool
    custom_response: typing.Any | None


class GetLoginAttemptsByIdsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    attempted_at: datetime.datetime
    endpoint_path: str
    username: str
    password: str
    was_fake_success: bool
    canary_path: str | None
    canary_ip_address: str | None
    canary_issued_at: datetime.datetime | None
    install_id: int | None
    install_ip_address: str | None
    install_attempted_at: datetime.datetime | None


class GetInstallAttemptsByIdsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    attempted_at: datetime.datetime
    path: str
    site_title: str
    username: str
    email: str
    password: str
    password_generated: bool


class GetHitRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    id_: int
    ip_address: str
    occurred_at: datetime.datetime
    method: str
    path: str
    query: str | None
    status_code: int
    user_agent: str | None
    headers: str
    body: memoryview | None
    body_size: int | None
    category: enums.PathCategory
    banned: bool
    custom_response: typing.Any | None


class GetIpActivityRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    requests: int
    distinct_paths: int
    login_attempts: int
    install_attempts: int
    first_seen_at: datetime.datetime | None
    last_seen_at: datetime.datetime | None
    banned_requests: int


class GetPatternTotalsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    requests: int
    login_attempts: int
    install_attempts: int
    addresses: int
    countries: int


class GetObservationSpanRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    first_seen_at: datetime.datetime
    last_seen_at: datetime.datetime


class CountCategoriesSinceRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    category: enums.PathCategory
    requests: int
    addresses: int


class TopPathsSinceRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    path: str
    category: enums.PathCategory
    requests: int
    addresses: int


class TopUserAgentsSinceRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    user_agent: str | None
    requests: int
    addresses: int


class CountRequestsPerHourSinceRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    hour: datetime.datetime
    requests: int


class TopUsernamesSinceRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    value: str
    attempts: int
    addresses: int


class TopPasswordsSinceRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    value: str
    attempts: int
    addresses: int


class TopCountriesRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    country_code: str | None
    requests: int
    addresses: int


class TopNetworksRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    asn: int | None
    as_organisation: str | None
    requests: int
    addresses: int


class BusiestAddressesRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    ip_address: str
    requests: int
    distinct_paths: int
    login_attempts: int
    first_seen_at: datetime.datetime | None
    last_seen_at: datetime.datetime | None
    country_code: str | None


class LongestSeenAddressesRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    ip_address: str
    requests: int
    distinct_paths: int
    login_attempts: int
    first_seen_at: datetime.datetime | None
    last_seen_at: datetime.datetime | None
    country_code: str | None


class ListToolkitsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    paths: int
    address_count: int
    addresses: collections.abc.Sequence[str]
    example_address: str


class ListMapPlacesRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    latitude: float
    longitude: float
    city: str | None
    country_code: str | None
    requests: int
    addresses: int


class ListAppliedMigrationsRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    version: int
    sha256: str


CREATE_TELEMETRY_HIT: typing.Final[typing.LiteralString] = """-- name: CreateTelemetryHit :exec
INSERT INTO telemetry_hits (
    ip_address, method, path, query, router_group, user_agent, headers, body, body_size, status_code,
    banned, rule_id
)
VALUES (
    %(p1)s, %(p2)s, %(p3)s, %(p4)s, %(p5)s,
    %(p6)s, %(p7)s, %(p8)s, %(p9)s, %(p10)s,
    %(p11)s, %(p12)s
)
"""

CREATE_CREDENTIAL_STUFFING_ATTEMPT: typing.Final[typing.LiteralString] = """-- name: CreateCredentialStuffingAttempt :one
WITH opened AS (
    SELECT id FROM install_attempts
    WHERE (username = %(p3)s OR email = %(p3)s)
      AND password = %(p4)s
    ORDER BY attempted_at DESC, id DESC
    LIMIT 1
)
INSERT INTO credential_stuffing_attempts (
    ip_address, endpoint_path, username, password, was_fake_success, canary_id, install_id
)
VALUES (
    %(p1)s, %(p2)s, %(p3)s, %(p4)s,
    EXISTS (SELECT 1 FROM opened),
    (SELECT id FROM canary_tokens WHERE token = %(p4)s),
    (SELECT id FROM opened)
)
RETURNING
    was_fake_success,
    EXISTS (
        SELECT 1 FROM install_attempts
        WHERE username = %(p3)s OR email = %(p3)s
    ) AS known_account
"""

CREATE_INSTALL_ATTEMPT: typing.Final[typing.LiteralString] = """-- name: CreateInstallAttempt :one
INSERT INTO install_attempts (
    ip_address, path, site_title, username, email, password, password_generated
)
VALUES (
    %(p1)s, %(p2)s, %(p3)s, %(p4)s,
    %(p5)s, %(p6)s, %(p7)s
)
RETURNING id
"""

CREATE_CANARY_TOKEN: typing.Final[typing.LiteralString] = """-- name: CreateCanaryToken :exec
INSERT INTO canary_tokens (token, path, ip_address)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

COUNT_LOGIN_ATTEMPTS_SINCE: typing.Final[typing.LiteralString] = """-- name: CountLoginAttemptsSince :one
SELECT count(*) AS attempts
FROM credential_stuffing_attempts
WHERE ip_address = %(p1)s::inet AND attempted_at >= %(p2)s::timestamptz
"""

CREATE_O_AUTH_STATE: typing.Final[typing.LiteralString] = """-- name: CreateOAuthState :exec

INSERT INTO oauth_states (state, code_verifier, expires)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

TAKE_O_AUTH_STATE: typing.Final[typing.LiteralString] = """-- name: TakeOAuthState :one
DELETE FROM oauth_states
WHERE state = %(p1)s AND expires > NOW()
RETURNING code_verifier
"""

PRUNE_O_AUTH_STATES: typing.Final[typing.LiteralString] = """-- name: PruneOAuthStates :exec
DELETE FROM oauth_states WHERE expires <= NOW()
"""

UPSERT_USER: typing.Final[typing.LiteralString] = """-- name: UpsertUser :one
INSERT INTO users (google_sub, email, name)
VALUES (%(p1)s, %(p2)s, %(p3)s)
ON CONFLICT (email)
DO UPDATE SET
    google_sub = EXCLUDED.google_sub,
    name = EXCLUDED.name,
    last_login = CURRENT_TIMESTAMP
RETURNING id
"""

CREATE_SESSION: typing.Final[typing.LiteralString] = """-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

USE_SESSION: typing.Final[typing.LiteralString] = """-- name: UseSession :one
UPDATE sessions s SET last_used = NOW()
FROM users u
WHERE s.token_hash = %(p1)s AND s.expires > NOW() AND u.id = s.user_id
RETURNING u.id, u.email, u.name
"""

DELETE_SESSION: typing.Final[typing.LiteralString] = """-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = %(p1)s
"""

PRUNE_SESSIONS: typing.Final[typing.LiteralString] = """-- name: PruneSessions :exec
DELETE FROM sessions WHERE expires <= NOW()
"""

CREATE_AUDIT_LOG_ENTRY: typing.Final[typing.LiteralString] = """-- name: CreateAuditLogEntry :exec
INSERT INTO admin_audit_log (user_id, action, target_ip, details)
VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s)
"""

LIST_ACTIVE_RULES: typing.Final[typing.LiteralString] = """-- name: ListActiveRules :many

SELECT id, method, path_pattern, condition, status_code, content_type, headers::TEXT AS headers, body,
    delay_ms
FROM response_rules
WHERE removed_at IS NULL AND (expires IS NULL OR expires > NOW())
ORDER BY position, id
"""

LIST_RULES: typing.Final[typing.LiteralString] = """-- name: ListRules :many
SELECT
    r.id, r.position, r.method, r.path_pattern, r.condition, r.status_code, r.content_type,
    r.headers::TEXT AS headers, r.body, r.delay_ms, r.expires, r.note, r.updated,
    (SELECT count(*) FROM telemetry_hits h WHERE h.rule_id = r.id) AS hits
FROM response_rules r
WHERE r.removed_at IS NULL
ORDER BY r.position, r.id
"""

CREATE_RULE: typing.Final[typing.LiteralString] = """-- name: CreateRule :one
INSERT INTO response_rules (
    position, method, path_pattern, condition, status_code, content_type, headers, body, delay_ms,
    expires, note, created_by_user_id
)
VALUES (
    (SELECT COALESCE(max(position), 0) + 1 FROM response_rules),
    %(p1)s, %(p2)s, %(p3)s, %(p4)s,
    %(p5)s, %(p6)s, %(p7)s, %(p8)s,
    %(p9)s, %(p10)s, %(p11)s
)
RETURNING id
"""

UPDATE_RULE: typing.Final[typing.LiteralString] = """-- name: UpdateRule :one
UPDATE response_rules
SET method = %(p1)s, path_pattern = %(p2)s,
    condition = %(p3)s, status_code = %(p4)s,
    content_type = %(p5)s, headers = %(p6)s, body = %(p7)s,
    delay_ms = %(p8)s, expires = %(p9)s, note = %(p10)s,
    updated = NOW()
WHERE id = %(p11)s AND removed_at IS NULL
RETURNING id
"""

SET_RULE_POSITION: typing.Final[typing.LiteralString] = """-- name: SetRulePosition :exec
UPDATE response_rules SET position = %(p1)s WHERE id = %(p2)s
"""

REMOVE_RULE: typing.Final[typing.LiteralString] = """-- name: RemoveRule :one
UPDATE response_rules SET removed_at = NOW()
WHERE id = %(p1)s AND removed_at IS NULL
RETURNING id
"""

GET_VISITOR_FACTS: typing.Final[typing.LiteralString] = """-- name: GetVisitorFacts :one
SELECT
    l.country_code, l.city, l.asn, l.as_organisation, a.requests, a.first_seen_at,
    (SELECT count(*) FROM credential_stuffing_attempts c
     WHERE c.ip_address = v.ip AND c.attempted_at >= %(p1)s::timestamptz) AS logins,
    EXISTS (SELECT 1 FROM canary_tokens t WHERE t.ip_address = v.ip) AS has_canary,
    EXISTS (SELECT 1 FROM ip_bans b WHERE b.ip_address = v.ip) AS banned_before
FROM (SELECT %(p2)s::inet AS ip) v
LEFT JOIN ip_locations l ON l.ip_address = v.ip
LEFT JOIN ip_activity a ON a.ip_address = v.ip
"""

LIST_AUDIT_LOG: typing.Final[typing.LiteralString] = """-- name: ListAuditLog :many
SELECT l.id, l.logged_at, u.email, l.action, l.target_ip, l.details::TEXT AS details
FROM admin_audit_log l
JOIN users u ON u.id = l.user_id
ORDER BY l.logged_at DESC, l.id DESC
LIMIT %(p1)s
"""

IS_IP_BANNED: typing.Final[typing.LiteralString] = """-- name: IsIpBanned :one

SELECT EXISTS (
    SELECT 1 FROM ip_bans
    WHERE ip_address = %(p1)s::inet
      AND revoked_at IS NULL AND (expires IS NULL OR expires > NOW())
) AS banned
"""

CREATE_IP_BAN: typing.Final[typing.LiteralString] = """-- name: CreateIpBan :one
INSERT INTO ip_bans (ip_address, expires, reason, added_by_user_id)
SELECT %(p1)s::inet, %(p2)s, %(p3)s, %(p4)s
WHERE NOT EXISTS (
    SELECT 1 FROM ip_bans
    WHERE ip_address = %(p1)s::inet
      AND revoked_at IS NULL AND (expires IS NULL OR expires > NOW())
)
RETURNING id
"""

REVOKE_IP_BAN: typing.Final[typing.LiteralString] = """-- name: RevokeIpBan :one
UPDATE ip_bans
SET revoked_at = NOW(), revoked_by_user_id = %(p1)s,
    revocation_reason = %(p2)s
WHERE id = %(p3)s
  AND revoked_at IS NULL AND (expires IS NULL OR expires > NOW())
RETURNING ip_address
"""

GET_ACTIVE_IP_BAN: typing.Final[typing.LiteralString] = """-- name: GetActiveIpBan :one
SELECT added, expires
FROM ip_bans
WHERE ip_address = %(p1)s::inet
  AND revoked_at IS NULL AND (expires IS NULL OR expires > NOW())
ORDER BY added
LIMIT 1
"""

LIST_IP_BANS: typing.Final[typing.LiteralString] = """-- name: ListIpBans :many
SELECT
    b.id, b.ip_address, b.added, b.expires, b.reason, a.email AS added_by, b.revoked_at,
    r.email AS revoked_by, b.revocation_reason,
    b.revoked_at IS NULL AND (b.expires IS NULL OR b.expires > NOW()) AS active
FROM ip_bans b
JOIN users a ON a.id = b.added_by_user_id
LEFT JOIN users r ON r.id = b.revoked_by_user_id
WHERE CASE
    WHEN %(p1)s::inet IS NULL
        THEN b.revoked_at IS NULL AND (b.expires IS NULL OR b.expires > NOW())
    ELSE b.ip_address = %(p1)s::inet
END
ORDER BY b.added DESC, b.id DESC
"""

LIST_RECENT_EVENTS: typing.Final[typing.LiteralString] = """-- name: ListRecentEvents :many
SELECT kind, id, ip_address, occurred_at FROM (
    (SELECT 'hit'::event_kind AS kind, id, ip_address, occurred_at
     FROM telemetry_hits
     WHERE router_group = 'honeypot' AND is_public_address(ip_address) AND occurred_at <= %(p1)s::timestamptz
       AND (occurred_at, 'hit'::event_kind, id) < (%(p1)s::timestamptz, %(p2)s::event_kind, %(p3)s::bigint)
     ORDER BY occurred_at DESC, id DESC
     LIMIT %(p4)s::int)
    UNION ALL
    (SELECT 'login_attempt'::event_kind AS kind, id, ip_address, attempted_at AS occurred_at
     FROM credential_stuffing_attempts
     WHERE is_public_address(ip_address) AND attempted_at <= %(p1)s::timestamptz
       AND (attempted_at, 'login_attempt'::event_kind, id) < (%(p1)s::timestamptz, %(p2)s::event_kind, %(p3)s::bigint)
     ORDER BY attempted_at DESC, id DESC
     LIMIT %(p4)s::int)
    UNION ALL
    (SELECT 'install_attempt'::event_kind AS kind, id, ip_address, attempted_at AS occurred_at
     FROM install_attempts
     WHERE is_public_address(ip_address) AND attempted_at <= %(p1)s::timestamptz
       AND (attempted_at, 'install_attempt'::event_kind, id) < (%(p1)s::timestamptz, %(p2)s::event_kind, %(p3)s::bigint)
     ORDER BY attempted_at DESC, id DESC
     LIMIT %(p4)s::int)
) AS page
ORDER BY occurred_at DESC, kind DESC, id DESC
LIMIT %(p4)s::int
"""

LIST_IP_EVENTS: typing.Final[typing.LiteralString] = """-- name: ListIpEvents :many
SELECT kind, id, ip_address, occurred_at FROM (
    (SELECT 'hit'::event_kind AS kind, id, ip_address, occurred_at
     FROM telemetry_hits
     WHERE router_group = 'honeypot' AND ip_address = %(p1)s::inet AND is_public_address(ip_address) AND occurred_at <= %(p2)s::timestamptz
       AND (occurred_at, 'hit'::event_kind, id) < (%(p2)s::timestamptz, %(p3)s::event_kind, %(p4)s::bigint)
     ORDER BY occurred_at DESC, id DESC
     LIMIT %(p5)s::int)
    UNION ALL
    (SELECT 'login_attempt'::event_kind AS kind, id, ip_address, attempted_at AS occurred_at
     FROM credential_stuffing_attempts
     WHERE ip_address = %(p1)s::inet AND is_public_address(ip_address) AND attempted_at <= %(p2)s::timestamptz
       AND (attempted_at, 'login_attempt'::event_kind, id) < (%(p2)s::timestamptz, %(p3)s::event_kind, %(p4)s::bigint)
     ORDER BY attempted_at DESC, id DESC
     LIMIT %(p5)s::int)
    UNION ALL
    (SELECT 'install_attempt'::event_kind AS kind, id, ip_address, attempted_at AS occurred_at
     FROM install_attempts
     WHERE ip_address = %(p1)s::inet AND is_public_address(ip_address) AND attempted_at <= %(p2)s::timestamptz
       AND (attempted_at, 'install_attempt'::event_kind, id) < (%(p2)s::timestamptz, %(p3)s::event_kind, %(p4)s::bigint)
     ORDER BY attempted_at DESC, id DESC
     LIMIT %(p5)s::int)
) AS page
ORDER BY occurred_at DESC, kind DESC, id DESC
LIMIT %(p5)s::int
"""

GET_HITS_BY_IDS: typing.Final[typing.LiteralString] = """-- name: GetHitsByIds :many
SELECT
    id, ip_address, occurred_at, method, path, query, status_code, user_agent,
    COALESCE(substring(body FROM 1 FOR 1024), ''::BYTEA)::BYTEA AS body_preview, body_size,
    path_category(path) AS category, banned,
    rule_id IS NOT NULL AS custom_response
FROM telemetry_hits
WHERE id = ANY(%(p1)s::BIGINT[])
"""

GET_LOGIN_ATTEMPTS_BY_IDS: typing.Final[typing.LiteralString] = """-- name: GetLoginAttemptsByIds :many
SELECT
    a.id, a.ip_address, a.attempted_at, a.endpoint_path, a.username, a.password,
    a.was_fake_success, c.path AS canary_path, c.ip_address AS canary_ip_address,
    c.issued_at AS canary_issued_at, i.id AS install_id, i.ip_address AS install_ip_address,
    i.attempted_at AS install_attempted_at
FROM credential_stuffing_attempts a
LEFT JOIN canary_tokens c ON c.id = a.canary_id AND is_public_address(c.ip_address)
LEFT JOIN install_attempts i ON i.id = a.install_id AND is_public_address(i.ip_address)
WHERE a.id = ANY(%(p1)s::BIGINT[])
"""

GET_INSTALL_ATTEMPTS_BY_IDS: typing.Final[typing.LiteralString] = """-- name: GetInstallAttemptsByIds :many
SELECT
    id, ip_address, attempted_at, path, site_title, username, email, password, password_generated
FROM install_attempts
WHERE id = ANY(%(p1)s::BIGINT[]) AND is_public_address(ip_address)
"""

LIST_INSTALL_LOGIN_IDS: typing.Final[typing.LiteralString] = """-- name: ListInstallLoginIds :many
SELECT id
FROM credential_stuffing_attempts
WHERE install_id = %(p1)s AND is_public_address(ip_address)
ORDER BY attempted_at, id
LIMIT %(p2)s
"""

COUNT_INSTALL_LOGINS: typing.Final[typing.LiteralString] = """-- name: CountInstallLogins :one
SELECT count(*) FROM credential_stuffing_attempts
WHERE install_id = %(p1)s AND is_public_address(ip_address)
"""

GET_HIT: typing.Final[typing.LiteralString] = """-- name: GetHit :one
SELECT
    id, ip_address, occurred_at, method, path, query, status_code, user_agent,
    headers::TEXT AS headers, body, body_size, path_category(path) AS category, banned,
    rule_id IS NOT NULL AS custom_response
FROM telemetry_hits
WHERE id = %(p1)s AND router_group = %(p2)s AND is_public_address(ip_address)
"""

CATEGORISE_PATH: typing.Final[typing.LiteralString] = """-- name: CategorisePath :one
SELECT path_category(%(p1)s::TEXT) AS category
"""

GET_IP_ACTIVITY: typing.Final[typing.LiteralString] = """-- name: GetIpActivity :one
SELECT
    requests, distinct_paths, login_attempts, install_attempts, first_seen_at, last_seen_at,
    banned_requests
FROM ip_activity
WHERE ip_address = %(p1)s::inet AND is_public_address(ip_address)
"""

CREATE_IP_LOCATION: typing.Final[typing.LiteralString] = """-- name: CreateIpLocation :exec
INSERT INTO ip_locations (
    ip_address, country_code, city, latitude, longitude, asn, as_organisation, source
)
VALUES (
    %(p1)s, %(p2)s, %(p3)s, %(p4)s,
    %(p5)s, %(p6)s, %(p7)s, %(p8)s
)
ON CONFLICT (ip_address) DO NOTHING
"""

GET_IP_LOCATIONS: typing.Final[typing.LiteralString] = """-- name: GetIpLocations :many
SELECT
    ip_address, country_code, city, latitude, longitude, asn, as_organisation, source, located_at
FROM ip_locations
WHERE ip_address = ANY(%(p1)s::INET[])
"""

LIST_UNLOCATED_ADDRESSES: typing.Final[typing.LiteralString] = """-- name: ListUnlocatedAddresses :many
SELECT a.ip_address
FROM ip_activity a
WHERE NOT EXISTS (SELECT FROM ip_locations l WHERE l.ip_address = a.ip_address)
ORDER BY a.ip_address
"""

GET_PATTERN_TOTALS: typing.Final[typing.LiteralString] = """-- name: GetPatternTotals :one

SELECT
    COALESCE(sum(a.requests), 0)::BIGINT AS requests,
    COALESCE(sum(a.login_attempts), 0)::BIGINT AS login_attempts,
    COALESCE(sum(a.install_attempts), 0)::BIGINT AS install_attempts,
    count(*) AS addresses,
    count(DISTINCT l.country_code) AS countries
FROM ip_activity a
LEFT JOIN ip_locations l USING (ip_address)
WHERE is_public_address(a.ip_address)
"""

GET_OBSERVATION_SPAN: typing.Final[typing.LiteralString] = """-- name: GetObservationSpan :one
SELECT min(first_seen_at)::TIMESTAMPTZ AS first_seen_at, max(last_seen_at)::TIMESTAMPTZ AS last_seen_at
FROM ip_activity
WHERE is_public_address(ip_address)
HAVING count(first_seen_at) > 0
"""

COUNT_REQUESTS_SINCE: typing.Final[typing.LiteralString] = """-- name: CountRequestsSince :one
SELECT count(*) AS requests
FROM telemetry_hits
WHERE router_group = 'honeypot' AND is_public_address(ip_address)
      AND occurred_at >= %(p1)s::TIMESTAMPTZ
"""

COUNT_CATEGORIES_SINCE: typing.Final[typing.LiteralString] = """-- name: CountCategoriesSince :many
WITH visits AS MATERIALIZED (
    SELECT path, ip_address, count(*) AS requests
    FROM telemetry_hits
    WHERE router_group = 'honeypot' AND is_public_address(ip_address)
      AND occurred_at >= %(p1)s::TIMESTAMPTZ
    GROUP BY path, ip_address
), categories AS MATERIALIZED (
    SELECT path, path_category(path) AS category FROM (SELECT DISTINCT path FROM visits) p
)
SELECT c.category, sum(v.requests)::BIGINT AS requests, count(DISTINCT v.ip_address) AS addresses
FROM visits v
JOIN categories c USING (path)
GROUP BY c.category
ORDER BY requests DESC, c.category
"""

TOP_PATHS_SINCE: typing.Final[typing.LiteralString] = """-- name: TopPathsSince :many
SELECT path, path_category(path) AS category, requests, addresses FROM (
    SELECT path, count(*) AS requests, count(DISTINCT ip_address) AS addresses
    FROM telemetry_hits
    WHERE router_group = 'honeypot' AND is_public_address(ip_address)
      AND occurred_at >= %(p1)s::TIMESTAMPTZ
    GROUP BY path
    ORDER BY requests DESC, path
    LIMIT %(p2)s::INT
) top
"""

TOP_USER_AGENTS_SINCE: typing.Final[typing.LiteralString] = """-- name: TopUserAgentsSince :many
SELECT user_agent, count(*) AS requests, count(DISTINCT ip_address) AS addresses
FROM telemetry_hits
WHERE router_group = 'honeypot' AND is_public_address(ip_address)
      AND occurred_at >= %(p1)s::TIMESTAMPTZ
GROUP BY user_agent
ORDER BY requests DESC, user_agent
LIMIT %(p2)s::INT
"""

COUNT_REQUESTS_PER_HOUR_SINCE: typing.Final[typing.LiteralString] = """-- name: CountRequestsPerHourSince :many
SELECT date_trunc('hour', occurred_at)::TIMESTAMPTZ AS hour, count(*) AS requests
FROM telemetry_hits
WHERE router_group = 'honeypot' AND is_public_address(ip_address)
      AND occurred_at >= %(p1)s::TIMESTAMPTZ
GROUP BY hour
ORDER BY hour
"""

TOP_USERNAMES_SINCE: typing.Final[typing.LiteralString] = """-- name: TopUsernamesSince :many
SELECT username AS value, count(*) AS attempts, count(DISTINCT ip_address) AS addresses
FROM credential_stuffing_attempts
WHERE attempted_at >= %(p1)s::TIMESTAMPTZ AND is_public_address(ip_address)
GROUP BY username
ORDER BY attempts DESC, username
LIMIT %(p2)s::INT
"""

TOP_PASSWORDS_SINCE: typing.Final[typing.LiteralString] = """-- name: TopPasswordsSince :many
SELECT password AS value, count(*) AS attempts, count(DISTINCT ip_address) AS addresses
FROM credential_stuffing_attempts
WHERE attempted_at >= %(p1)s::TIMESTAMPTZ AND is_public_address(ip_address)
GROUP BY password
ORDER BY attempts DESC, password
LIMIT %(p2)s::INT
"""

TOP_COUNTRIES: typing.Final[typing.LiteralString] = """-- name: TopCountries :many
SELECT l.country_code, sum(a.requests)::BIGINT AS requests, count(*) AS addresses
FROM ip_activity a
LEFT JOIN ip_locations l USING (ip_address)
WHERE is_public_address(a.ip_address)
GROUP BY l.country_code
ORDER BY requests DESC, l.country_code
LIMIT %(p1)s::INT
"""

TOP_NETWORKS: typing.Final[typing.LiteralString] = """-- name: TopNetworks :many
SELECT l.asn, l.as_organisation, sum(a.requests)::BIGINT AS requests, count(*) AS addresses
FROM ip_activity a
LEFT JOIN ip_locations l USING (ip_address)
WHERE is_public_address(a.ip_address)
GROUP BY l.asn, l.as_organisation
ORDER BY requests DESC, l.asn
LIMIT %(p1)s::INT
"""

BUSIEST_ADDRESSES: typing.Final[typing.LiteralString] = """-- name: BusiestAddresses :many
SELECT
    a.ip_address, a.requests, a.distinct_paths, a.login_attempts, a.first_seen_at,
    a.last_seen_at, l.country_code
FROM ip_activity a
LEFT JOIN ip_locations l USING (ip_address)
WHERE is_public_address(a.ip_address)
ORDER BY a.requests DESC, a.ip_address
LIMIT %(p1)s::INT
"""

LONGEST_SEEN_ADDRESSES: typing.Final[typing.LiteralString] = """-- name: LongestSeenAddresses :many
SELECT
    a.ip_address, a.requests, a.distinct_paths, a.login_attempts, a.first_seen_at,
    a.last_seen_at, l.country_code
FROM ip_activity a
LEFT JOIN ip_locations l USING (ip_address)
WHERE a.first_seen_at IS NOT NULL AND is_public_address(a.ip_address)
ORDER BY a.last_seen_at - a.first_seen_at DESC, a.ip_address
LIMIT %(p1)s::INT
"""

LIST_TOOLKITS: typing.Final[typing.LiteralString] = """-- name: ListToolkits :many
WITH path_sets AS (
    SELECT ip_address, md5(string_agg(path_md5::TEXT, ',' ORDER BY path_md5)) AS path_set,
           count(*) AS paths
    FROM ip_request_paths
    WHERE is_public_address(ip_address)
    GROUP BY ip_address
    HAVING count(*) >= %(p3)s::INT
)
SELECT
    max(s.paths)::BIGINT AS paths,
    count(*) AS address_count,
    (array_agg(s.ip_address ORDER BY a.requests DESC, s.ip_address))[1:%(p1)s::INT]::INET[]
        AS addresses,
    (array_agg(s.ip_address ORDER BY a.requests, s.ip_address))[1]::INET AS example_address
FROM path_sets s
JOIN ip_activity a USING (ip_address)
GROUP BY s.path_set
HAVING count(*) >= 2
ORDER BY address_count DESC, paths DESC
LIMIT %(p2)s::INT
"""

LIST_PATHS_OF: typing.Final[typing.LiteralString] = """-- name: ListPathsOf :many
SELECT DISTINCT path
FROM telemetry_hits
WHERE ip_address = %(p1)s::INET AND router_group = 'honeypot'
  AND is_public_address(ip_address)
ORDER BY path
LIMIT %(p2)s::INT
"""

LIST_MAP_PLACES: typing.Final[typing.LiteralString] = """-- name: ListMapPlaces :many
SELECT
    l.latitude::FLOAT8 AS latitude, l.longitude::FLOAT8 AS longitude, l.city, l.country_code,
    sum(a.requests)::BIGINT AS requests, count(*) AS addresses
FROM ip_activity a
JOIN ip_locations l USING (ip_address)
WHERE l.latitude IS NOT NULL AND is_public_address(a.ip_address)
GROUP BY l.latitude, l.longitude, l.city, l.country_code
ORDER BY requests DESC
LIMIT %(p1)s::INT
"""

DROP_PUBLIC_SCHEMA: typing.Final[typing.LiteralString] = """-- name: DropPublicSchema :exec
DROP SCHEMA IF EXISTS public CASCADE
"""

CREATE_PUBLIC_SCHEMA: typing.Final[typing.LiteralString] = """-- name: CreatePublicSchema :exec
CREATE SCHEMA public
"""

LIST_APPLIED_MIGRATIONS: typing.Final[typing.LiteralString] = """-- name: ListAppliedMigrations :many
SELECT version, sha256 FROM schema_migrations ORDER BY version
"""

RECORD_MIGRATION: typing.Final[typing.LiteralString] = """-- name: RecordMigration :exec
INSERT INTO schema_migrations (version, name, sha256)
VALUES (%(p1)s, %(p2)s, %(p3)s)
"""

SEED_HITS: typing.Final[typing.LiteralString] = """-- name: SeedHits :exec
INSERT INTO telemetry_hits (
    ip_address, method, path, query, router_group, user_agent, headers, body, body_size,
    status_code, occurred_at
)
SELECT
    %(p1)s::inet + CASE
        WHEN random() < %(p2)s::float8 THEN 0
        ELSE floor(%(p3)s::int * power(random(), 3))::int
    END,
    hit.method, hit.path, NULLIF(hit.query, ''), 'honeypot', hit.user_agent,
    jsonb_build_object('host', 'seed.invalid', 'user-agent', hit.user_agent),
    hit.body, octet_length(hit.body), hit.status_code,
    now() - make_interval(days => %(p4)s::int)
        + (n::float8 / %(p5)s::int) * make_interval(days => %(p4)s::int)
FROM generate_series(%(p6)s::int + 1, %(p6)s::int + %(p7)s::int) n
CROSS JOIN LATERAL (
    SELECT
        CASE WHEN r < 0.2 THEN 'POST' ELSE 'GET' END AS method,
        (ARRAY['/wp-login.php', '/.env', '/xmlrpc.php', '/phpmyadmin/', '/', '/admin',
               '/.git/config', '/cgi-bin/luci', '/boaform/admin/formLogin',
               '/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'])[1 + floor(random() * 10)::int]
            AS path,
        CASE WHEN random() < 0.1 THEN 'id=' || n ELSE '' END AS query,
        (ARRAY['Mozilla/5.0 zgrab/0.x', 'curl/8.5.0', 'python-requests/2.32',
               'Go-http-client/1.1'])[1 + floor(random() * 4)::int] AS user_agent,
        CASE
            WHEN r >= 0.2 THEN ''::BYTEA
            WHEN random() < 0.01 THEN convert_to(repeat(md5(random()::text), 2048), 'UTF8')
            ELSE convert_to(repeat(md5(random()::text), 1 + floor(random() * 16)::int), 'UTF8')
        END AS body,
        CASE WHEN random() < 0.05 THEN 200 ELSE 404 END AS status_code
    FROM (SELECT random() AS r, n) draw
) hit
ORDER BY n
"""

SEED_LOGIN_ATTEMPTS: typing.Final[typing.LiteralString] = """-- name: SeedLoginAttempts :exec
INSERT INTO credential_stuffing_attempts (ip_address, endpoint_path, username, password, attempted_at)
SELECT
    %(p1)s::inet + CASE
        WHEN random() < %(p2)s::float8 THEN 0
        ELSE floor(%(p3)s::int * power(random(), 3))::int
    END,
    '/wp-login.php',
    (ARRAY['admin', 'root', 'administrator', 'test', 'user'])[1 + floor(random() * 5)::int],
    (ARRAY['admin', '123456', 'password', 'admin123', 'qwerty'])[1 + floor(random() * 5)::int],
    now() - make_interval(days => %(p4)s::int)
        + (n::float8 / %(p5)s::int) * make_interval(days => %(p4)s::int)
FROM generate_series(%(p6)s::int + 1, %(p6)s::int + %(p7)s::int) n
ORDER BY n
"""


class QueryResults[T]:
    __slots__ = ("_conn", "_cursor", "_decode_hook", "_iterator", "_params", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: typing.LiteralString,
        decode_hook: collections.abc.Callable[[psycopg.rows.TupleRow], T],
        params: dict[str, QueryResultsArgsType] | None = None,
    ) -> None:
        self._conn = conn
        self._sql: typing.LiteralString = sql
        self._decode_hook = decode_hook
        self._params = params
        self._cursor: psycopg.AsyncCursor[psycopg.rows.TupleRow] | None = None
        self._iterator: collections.abc.AsyncIterator[psycopg.rows.TupleRow] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await (await self._conn.execute(self._sql, self._params)).fetchall()
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = await self._conn.execute(self._sql, self._params)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def create_telemetry_hit(conn: ConnectionLike, *, ip_address: str, method: str, path: str, query: str | None, router_group: enums.RouterGroup, user_agent: str | None, headers: str, body: memoryview | None, body_size: int | None, status_code: int, banned: bool, rule_id: int | None) -> None:
    await conn.execute(CREATE_TELEMETRY_HIT, {"p1": ip_address, "p2": method, "p3": path, "p4": query, "p5": router_group, "p6": user_agent, "p7": headers, "p8": body, "p9": body_size, "p10": status_code, "p11": banned, "p12": rule_id})


async def create_credential_stuffing_attempt(conn: ConnectionLike, *, ip_address: str, endpoint_path: str, username: str, password: str) -> CreateCredentialStuffingAttemptRow | None:
    row = await (await conn.execute(CREATE_CREDENTIAL_STUFFING_ATTEMPT, {"p1": ip_address, "p2": endpoint_path, "p3": username, "p4": password})).fetchone()
    if row is None:
        return None
    return CreateCredentialStuffingAttemptRow(was_fake_success=row[0], known_account=row[1])


async def create_install_attempt(conn: ConnectionLike, *, ip_address: str, path: str, site_title: str, username: str, email: str, password: str, password_generated: bool) -> int | None:
    row = await (await conn.execute(CREATE_INSTALL_ATTEMPT, {"p1": ip_address, "p2": path, "p3": site_title, "p4": username, "p5": email, "p6": password, "p7": password_generated})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_canary_token(conn: ConnectionLike, *, token: str, path: str, ip_address: str) -> None:
    await conn.execute(CREATE_CANARY_TOKEN, {"p1": token, "p2": path, "p3": ip_address})


async def count_login_attempts_since(conn: ConnectionLike, *, ip_address: str, since: datetime.datetime) -> int | None:
    row = await (await conn.execute(COUNT_LOGIN_ATTEMPTS_SINCE, {"p1": ip_address, "p2": since})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_o_auth_state(conn: ConnectionLike, *, state: str, code_verifier: str, expires: datetime.datetime) -> None:
    await conn.execute(CREATE_O_AUTH_STATE, {"p1": state, "p2": code_verifier, "p3": expires})


async def take_o_auth_state(conn: ConnectionLike, *, state: str) -> str | None:
    row = await (await conn.execute(TAKE_O_AUTH_STATE, {"p1": state})).fetchone()
    if row is None:
        return None
    return row[0]


async def prune_o_auth_states(conn: ConnectionLike) -> None:
    await conn.execute(PRUNE_O_AUTH_STATES)


async def upsert_user(conn: ConnectionLike, *, google_sub: str, email: str, name: str) -> int | None:
    row = await (await conn.execute(UPSERT_USER, {"p1": google_sub, "p2": email, "p3": name})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_session(conn: ConnectionLike, *, user_id: int, token_hash: str, expires: datetime.datetime) -> None:
    await conn.execute(CREATE_SESSION, {"p1": user_id, "p2": token_hash, "p3": expires})


async def use_session(conn: ConnectionLike, *, token_hash: str) -> UseSessionRow | None:
    row = await (await conn.execute(USE_SESSION, {"p1": token_hash})).fetchone()
    if row is None:
        return None
    return UseSessionRow(id_=row[0], email=row[1], name=row[2])


async def delete_session(conn: ConnectionLike, *, token_hash: str) -> None:
    await conn.execute(DELETE_SESSION, {"p1": token_hash})


async def prune_sessions(conn: ConnectionLike) -> None:
    await conn.execute(PRUNE_SESSIONS)


async def create_audit_log_entry(conn: ConnectionLike, *, user_id: int, action: enums.AuditAction, target_ip: str | None, details: str) -> None:
    await conn.execute(CREATE_AUDIT_LOG_ENTRY, {"p1": user_id, "p2": action, "p3": target_ip, "p4": details})


def list_active_rules(conn: ConnectionLike) -> QueryResults[ListActiveRulesRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListActiveRulesRow:
        return ListActiveRulesRow(id_=row[0], method=row[1], path_pattern=row[2], condition=row[3], status_code=row[4], content_type=row[5], headers=row[6], body=row[7], delay_ms=row[8])

    return QueryResults(conn, LIST_ACTIVE_RULES, _decode_hook)


def list_rules(conn: ConnectionLike) -> QueryResults[ListRulesRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListRulesRow:
        return ListRulesRow(id_=row[0], position=row[1], method=row[2], path_pattern=row[3], condition=row[4], status_code=row[5], content_type=row[6], headers=row[7], body=row[8], delay_ms=row[9], expires=row[10], note=row[11], updated=row[12], hits=row[13])

    return QueryResults(conn, LIST_RULES, _decode_hook)


async def create_rule(conn: ConnectionLike, *, method: str | None, path_pattern: str | None, condition: str, status_code: int, content_type: str, headers: str, body: str, delay_ms: int, expires: datetime.datetime | None, note: str | None, created_by_user_id: int) -> int | None:
    row = await (await conn.execute(CREATE_RULE, {"p1": method, "p2": path_pattern, "p3": condition, "p4": status_code, "p5": content_type, "p6": headers, "p7": body, "p8": delay_ms, "p9": expires, "p10": note, "p11": created_by_user_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def update_rule(conn: ConnectionLike, *, method: str | None, path_pattern: str | None, condition: str, status_code: int, content_type: str, headers: str, body: str, delay_ms: int, expires: datetime.datetime | None, note: str | None, id_: int) -> int | None:
    row = await (await conn.execute(UPDATE_RULE, {"p1": method, "p2": path_pattern, "p3": condition, "p4": status_code, "p5": content_type, "p6": headers, "p7": body, "p8": delay_ms, "p9": expires, "p10": note, "p11": id_})).fetchone()
    if row is None:
        return None
    return row[0]


async def set_rule_position(conn: ConnectionLike, *, position: int, id_: int) -> None:
    await conn.execute(SET_RULE_POSITION, {"p1": position, "p2": id_})


async def remove_rule(conn: ConnectionLike, *, id_: int) -> int | None:
    row = await (await conn.execute(REMOVE_RULE, {"p1": id_})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_visitor_facts(conn: ConnectionLike, *, logins_since: datetime.datetime, ip_address: str) -> GetVisitorFactsRow | None:
    row = await (await conn.execute(GET_VISITOR_FACTS, {"p1": logins_since, "p2": ip_address})).fetchone()
    if row is None:
        return None
    return GetVisitorFactsRow(country_code=row[0], city=row[1], asn=row[2], as_organisation=row[3], requests=row[4], first_seen_at=row[5], logins=row[6], has_canary=row[7], banned_before=row[8])


def list_audit_log(conn: ConnectionLike, *, limit_: int) -> QueryResults[ListAuditLogRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListAuditLogRow:
        return ListAuditLogRow(id_=row[0], logged_at=row[1], email=row[2], action=enums.AuditAction(row[3]), target_ip=str(row[4]) if row[4] is not None else None, details=row[5])

    return QueryResults(conn, LIST_AUDIT_LOG, _decode_hook, {"p1": limit_})


async def is_ip_banned(conn: ConnectionLike, *, ip_address: str) -> bool | None:
    row = await (await conn.execute(IS_IP_BANNED, {"p1": ip_address})).fetchone()
    if row is None:
        return None
    return row[0]


async def create_ip_ban(conn: ConnectionLike, *, ip_address: str, expires: datetime.datetime | None, reason: str | None, added_by_user_id: int) -> int | None:
    row = await (await conn.execute(CREATE_IP_BAN, {"p1": ip_address, "p2": expires, "p3": reason, "p4": added_by_user_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def revoke_ip_ban(conn: ConnectionLike, *, revoked_by_user_id: int | None, revocation_reason: str | None, id_: int) -> str | None:
    row = await (await conn.execute(REVOKE_IP_BAN, {"p1": revoked_by_user_id, "p2": revocation_reason, "p3": id_})).fetchone()
    if row is None:
        return None
    return str(row[0])


async def get_active_ip_ban(conn: ConnectionLike, *, ip_address: str) -> GetActiveIpBanRow | None:
    row = await (await conn.execute(GET_ACTIVE_IP_BAN, {"p1": ip_address})).fetchone()
    if row is None:
        return None
    return GetActiveIpBanRow(added=row[0], expires=row[1])


def list_ip_bans(conn: ConnectionLike, *, ip_address: str | None) -> QueryResults[ListIpBansRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListIpBansRow:
        return ListIpBansRow(id_=row[0], ip_address=str(row[1]), added=row[2], expires=row[3], reason=row[4], added_by=row[5], revoked_at=row[6], revoked_by=row[7], revocation_reason=row[8], active=row[9])

    return QueryResults(conn, LIST_IP_BANS, _decode_hook, {"p1": ip_address})


def list_recent_events(conn: ConnectionLike, *, before_at: datetime.datetime, before_kind: enums.EventKind, before_id: int, limit: int) -> QueryResults[ListRecentEventsRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListRecentEventsRow:
        return ListRecentEventsRow(kind=enums.EventKind(row[0]), id_=row[1], ip_address=str(row[2]), occurred_at=row[3])

    return QueryResults(conn, LIST_RECENT_EVENTS, _decode_hook, {"p1": before_at, "p2": before_kind, "p3": before_id, "p4": limit})


def list_ip_events(conn: ConnectionLike, *, ip_address: str, before_at: datetime.datetime, before_kind: enums.EventKind, before_id: int, limit: int) -> QueryResults[ListIpEventsRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListIpEventsRow:
        return ListIpEventsRow(kind=enums.EventKind(row[0]), id_=row[1], ip_address=str(row[2]), occurred_at=row[3])

    return QueryResults(conn, LIST_IP_EVENTS, _decode_hook, {"p1": ip_address, "p2": before_at, "p3": before_kind, "p4": before_id, "p5": limit})


def get_hits_by_ids(conn: ConnectionLike, *, ids: collections.abc.Sequence[int]) -> QueryResults[GetHitsByIdsRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> GetHitsByIdsRow:
        return GetHitsByIdsRow(id_=row[0], ip_address=str(row[1]), occurred_at=row[2], method=row[3], path=row[4], query=row[5], status_code=row[6], user_agent=row[7], body_preview=memoryview(row[8]), body_size=row[9], category=enums.PathCategory(row[10]), banned=row[11], custom_response=row[12])

    return QueryResults(conn, GET_HITS_BY_IDS, _decode_hook, {"p1": list(ids)})


def get_login_attempts_by_ids(conn: ConnectionLike, *, ids: collections.abc.Sequence[int]) -> QueryResults[GetLoginAttemptsByIdsRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> GetLoginAttemptsByIdsRow:
        return GetLoginAttemptsByIdsRow(
            id_=row[0],
            ip_address=str(row[1]),
            attempted_at=row[2],
            endpoint_path=row[3],
            username=row[4],
            password=row[5],
            was_fake_success=row[6],
            canary_path=row[7],
            canary_ip_address=str(row[8]) if row[8] is not None else None,
            canary_issued_at=row[9],
            install_id=row[10],
            install_ip_address=str(row[11]) if row[11] is not None else None,
            install_attempted_at=row[12],
        )

    return QueryResults(conn, GET_LOGIN_ATTEMPTS_BY_IDS, _decode_hook, {"p1": list(ids)})


def get_install_attempts_by_ids(conn: ConnectionLike, *, ids: collections.abc.Sequence[int]) -> QueryResults[GetInstallAttemptsByIdsRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> GetInstallAttemptsByIdsRow:
        return GetInstallAttemptsByIdsRow(id_=row[0], ip_address=str(row[1]), attempted_at=row[2], path=row[3], site_title=row[4], username=row[5], email=row[6], password=row[7], password_generated=row[8])

    return QueryResults(conn, GET_INSTALL_ATTEMPTS_BY_IDS, _decode_hook, {"p1": list(ids)})


def list_install_login_ids(conn: ConnectionLike, *, install_id: int | None, max_rows: int) -> QueryResults[int]:
    return QueryResults(conn, LIST_INSTALL_LOGIN_IDS, operator.itemgetter(0), {"p1": install_id, "p2": max_rows})


async def count_install_logins(conn: ConnectionLike, *, install_id: int | None) -> int | None:
    row = await (await conn.execute(COUNT_INSTALL_LOGINS, {"p1": install_id})).fetchone()
    if row is None:
        return None
    return row[0]


async def get_hit(conn: ConnectionLike, *, id_: int, router_group: enums.RouterGroup) -> GetHitRow | None:
    row = await (await conn.execute(GET_HIT, {"p1": id_, "p2": router_group})).fetchone()
    if row is None:
        return None
    return GetHitRow(
        id_=row[0],
        ip_address=str(row[1]),
        occurred_at=row[2],
        method=row[3],
        path=row[4],
        query=row[5],
        status_code=row[6],
        user_agent=row[7],
        headers=row[8],
        body=memoryview(row[9]) if row[9] is not None else None,
        body_size=row[10],
        category=enums.PathCategory(row[11]),
        banned=row[12],
        custom_response=row[13],
    )


async def categorise_path(conn: ConnectionLike, *, path: str) -> enums.PathCategory | None:
    row = await (await conn.execute(CATEGORISE_PATH, {"p1": path})).fetchone()
    if row is None:
        return None
    return enums.PathCategory(row[0])


async def get_ip_activity(conn: ConnectionLike, *, ip_address: str) -> GetIpActivityRow | None:
    row = await (await conn.execute(GET_IP_ACTIVITY, {"p1": ip_address})).fetchone()
    if row is None:
        return None
    return GetIpActivityRow(requests=row[0], distinct_paths=row[1], login_attempts=row[2], install_attempts=row[3], first_seen_at=row[4], last_seen_at=row[5], banned_requests=row[6])


async def create_ip_location(conn: ConnectionLike, *, ip_address: str, country_code: str | None, city: str | None, latitude: float | None, longitude: float | None, asn: int | None, as_organisation: str | None, source: str) -> None:
    await conn.execute(CREATE_IP_LOCATION, {"p1": ip_address, "p2": country_code, "p3": city, "p4": latitude, "p5": longitude, "p6": asn, "p7": as_organisation, "p8": source})


def get_ip_locations(conn: ConnectionLike, *, ip_addresses: collections.abc.Sequence[str]) -> QueryResults[models.IpLocation]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> models.IpLocation:
        return models.IpLocation(ip_address=str(row[0]), country_code=row[1], city=row[2], latitude=row[3], longitude=row[4], asn=row[5], as_organisation=row[6], source=row[7], located_at=row[8])

    return QueryResults(conn, GET_IP_LOCATIONS, _decode_hook, {"p1": list(ip_addresses)})


def list_unlocated_addresses(conn: ConnectionLike) -> QueryResults[str]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> str:
        return str(row[0])

    return QueryResults(conn, LIST_UNLOCATED_ADDRESSES, _decode_hook)


async def get_pattern_totals(conn: ConnectionLike) -> GetPatternTotalsRow | None:
    row = await (await conn.execute(GET_PATTERN_TOTALS)).fetchone()
    if row is None:
        return None
    return GetPatternTotalsRow(requests=row[0], login_attempts=row[1], install_attempts=row[2], addresses=row[3], countries=row[4])


async def get_observation_span(conn: ConnectionLike) -> GetObservationSpanRow | None:
    row = await (await conn.execute(GET_OBSERVATION_SPAN)).fetchone()
    if row is None:
        return None
    return GetObservationSpanRow(first_seen_at=row[0], last_seen_at=row[1])


async def count_requests_since(conn: ConnectionLike, *, since: datetime.datetime) -> int | None:
    row = await (await conn.execute(COUNT_REQUESTS_SINCE, {"p1": since})).fetchone()
    if row is None:
        return None
    return row[0]


def count_categories_since(conn: ConnectionLike, *, since: datetime.datetime) -> QueryResults[CountCategoriesSinceRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> CountCategoriesSinceRow:
        return CountCategoriesSinceRow(category=enums.PathCategory(row[0]), requests=row[1], addresses=row[2])

    return QueryResults(conn, COUNT_CATEGORIES_SINCE, _decode_hook, {"p1": since})


def top_paths_since(conn: ConnectionLike, *, since: datetime.datetime, limit: int) -> QueryResults[TopPathsSinceRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> TopPathsSinceRow:
        return TopPathsSinceRow(path=row[0], category=enums.PathCategory(row[1]), requests=row[2], addresses=row[3])

    return QueryResults(conn, TOP_PATHS_SINCE, _decode_hook, {"p1": since, "p2": limit})


def top_user_agents_since(conn: ConnectionLike, *, since: datetime.datetime, limit: int) -> QueryResults[TopUserAgentsSinceRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> TopUserAgentsSinceRow:
        return TopUserAgentsSinceRow(user_agent=row[0], requests=row[1], addresses=row[2])

    return QueryResults(conn, TOP_USER_AGENTS_SINCE, _decode_hook, {"p1": since, "p2": limit})


def count_requests_per_hour_since(conn: ConnectionLike, *, since: datetime.datetime) -> QueryResults[CountRequestsPerHourSinceRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> CountRequestsPerHourSinceRow:
        return CountRequestsPerHourSinceRow(hour=row[0], requests=row[1])

    return QueryResults(conn, COUNT_REQUESTS_PER_HOUR_SINCE, _decode_hook, {"p1": since})


def top_usernames_since(conn: ConnectionLike, *, since: datetime.datetime, limit: int) -> QueryResults[TopUsernamesSinceRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> TopUsernamesSinceRow:
        return TopUsernamesSinceRow(value=row[0], attempts=row[1], addresses=row[2])

    return QueryResults(conn, TOP_USERNAMES_SINCE, _decode_hook, {"p1": since, "p2": limit})


def top_passwords_since(conn: ConnectionLike, *, since: datetime.datetime, limit: int) -> QueryResults[TopPasswordsSinceRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> TopPasswordsSinceRow:
        return TopPasswordsSinceRow(value=row[0], attempts=row[1], addresses=row[2])

    return QueryResults(conn, TOP_PASSWORDS_SINCE, _decode_hook, {"p1": since, "p2": limit})


def top_countries(conn: ConnectionLike, *, limit: int) -> QueryResults[TopCountriesRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> TopCountriesRow:
        return TopCountriesRow(country_code=row[0], requests=row[1], addresses=row[2])

    return QueryResults(conn, TOP_COUNTRIES, _decode_hook, {"p1": limit})


def top_networks(conn: ConnectionLike, *, limit: int) -> QueryResults[TopNetworksRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> TopNetworksRow:
        return TopNetworksRow(asn=row[0], as_organisation=row[1], requests=row[2], addresses=row[3])

    return QueryResults(conn, TOP_NETWORKS, _decode_hook, {"p1": limit})


def busiest_addresses(conn: ConnectionLike, *, limit: int) -> QueryResults[BusiestAddressesRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> BusiestAddressesRow:
        return BusiestAddressesRow(ip_address=str(row[0]), requests=row[1], distinct_paths=row[2], login_attempts=row[3], first_seen_at=row[4], last_seen_at=row[5], country_code=row[6])

    return QueryResults(conn, BUSIEST_ADDRESSES, _decode_hook, {"p1": limit})


def longest_seen_addresses(conn: ConnectionLike, *, limit: int) -> QueryResults[LongestSeenAddressesRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> LongestSeenAddressesRow:
        return LongestSeenAddressesRow(ip_address=str(row[0]), requests=row[1], distinct_paths=row[2], login_attempts=row[3], first_seen_at=row[4], last_seen_at=row[5], country_code=row[6])

    return QueryResults(conn, LONGEST_SEEN_ADDRESSES, _decode_hook, {"p1": limit})


def list_toolkits(conn: ConnectionLike, *, max_addresses: int, limit: int, min_paths: int) -> QueryResults[ListToolkitsRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListToolkitsRow:
        return ListToolkitsRow(paths=row[0], address_count=row[1], addresses=[str(v) for v in row[2]], example_address=str(row[3]))

    return QueryResults(conn, LIST_TOOLKITS, _decode_hook, {"p1": max_addresses, "p2": limit, "p3": min_paths})


def list_paths_of(conn: ConnectionLike, *, ip_address: str, limit: int) -> QueryResults[str]:
    return QueryResults(conn, LIST_PATHS_OF, operator.itemgetter(0), {"p1": ip_address, "p2": limit})


def list_map_places(conn: ConnectionLike, *, limit: int) -> QueryResults[ListMapPlacesRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListMapPlacesRow:
        return ListMapPlacesRow(latitude=row[0], longitude=row[1], city=row[2], country_code=row[3], requests=row[4], addresses=row[5])

    return QueryResults(conn, LIST_MAP_PLACES, _decode_hook, {"p1": limit})


async def drop_public_schema(conn: ConnectionLike) -> None:
    await conn.execute(DROP_PUBLIC_SCHEMA)


async def create_public_schema(conn: ConnectionLike) -> None:
    await conn.execute(CREATE_PUBLIC_SCHEMA)


def list_applied_migrations(conn: ConnectionLike) -> QueryResults[ListAppliedMigrationsRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListAppliedMigrationsRow:
        return ListAppliedMigrationsRow(version=row[0], sha256=row[1])

    return QueryResults(conn, LIST_APPLIED_MIGRATIONS, _decode_hook)


async def record_migration(conn: ConnectionLike, *, version: int, name: str, sha256: str) -> None:
    await conn.execute(RECORD_MIGRATION, {"p1": version, "p2": name, "p3": sha256})


async def seed_hits(conn: ConnectionLike, *, first_address: str, busy_share: float, addresses: int, days: int, total: int, start: int, count: int) -> None:
    await conn.execute(SEED_HITS, {"p1": first_address, "p2": busy_share, "p3": addresses, "p4": days, "p5": total, "p6": start, "p7": count})


async def seed_login_attempts(conn: ConnectionLike, *, first_address: str, busy_share: float, addresses: int, days: int, total: int, start: int, count: int) -> None:
    await conn.execute(SEED_LOGIN_ATTEMPTS, {"p1": first_address, "p2": busy_share, "p3": addresses, "p4": days, "p5": total, "p6": start, "p7": count})
