# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: queries.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetIpThreatSummaryRow",
    "ListIpActivityRow",
    "QueryResults",
    "create_active_ip_ban",
    "create_credential_stuffing_attempt",
    "create_telemetry_hit",
    "get_ip_threat_summary",
    "get_user_by_session_token_hash",
    "list_ip_activity",
    "upsert_user",
)

import datetime
import pydantic
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import psycopg
    import psycopg.rows

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = psycopg.AsyncConnection[psycopg.rows.TupleRow]

from . import models


class GetIpThreatSummaryRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    ip_address: str
    total_requests: int
    unique_endpoints_probed: int
    last_seen_at: typing.Any


class ListIpActivityRow(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(arbitrary_types_allowed=True)

    event_at: datetime.datetime
    event_type: str
    target_id: int
    target_slug: str
    details: str


UPSERT_USER: typing.Final[typing.LiteralString] = """-- name: UpsertUser :one
INSERT INTO users (google_sub, email, name, is_admin)
VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s)
ON CONFLICT (google_sub)
DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    last_login = CURRENT_TIMESTAMP,
    is_admin = EXCLUDED.is_admin
RETURNING id, google_sub, email, name, created, last_login, is_admin
"""

GET_USER_BY_SESSION_TOKEN_HASH: typing.Final[typing.LiteralString] = """-- name: GetUserBySessionTokenHash :one
SELECT 
    u.id, u.google_sub, u.email, u.name, u.created, u.last_login, u.is_admin
FROM users u
INNER JOIN sessions s ON u.id = s.user_id
WHERE s.token_hash = %(p1)s
  AND s.expires > NOW()
"""

CREATE_TELEMETRY_HIT: typing.Final[typing.LiteralString] = """-- name: CreateTelemetryHit :exec
INSERT INTO telemetry_hits (
    ip_address, method, path, router_group, user_agent, headers, status_code
)
VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s, %(p5)s, %(p6)s, %(p7)s)
"""

CREATE_CREDENTIAL_STUFFING_ATTEMPT: typing.Final[typing.LiteralString] = """-- name: CreateCredentialStuffingAttempt :exec
INSERT INTO credential_stuffing_attempts (
    ip_address, endpoint_path, username, password, was_fake_success
)
VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s, %(p5)s)
"""

GET_IP_THREAT_SUMMARY: typing.Final[typing.LiteralString] = """-- name: GetIpThreatSummary :one
SELECT
    ip_address,
    COUNT(*)::BIGINT AS total_requests,
    COUNT(DISTINCT path)::BIGINT AS unique_endpoints_probed,
    MAX(occurred_at) AS last_seen_at
FROM telemetry_hits
WHERE ip_address = %(p1)s::inet
GROUP BY ip_address
"""

CREATE_ACTIVE_IP_BAN: typing.Final[typing.LiteralString] = """-- name: CreateActiveIpBan :one
INSERT INTO ip_bans (ip_address, expires, reason, added_by_user_id)
VALUES (%(p1)s, %(p2)s, %(p3)s, %(p4)s)
RETURNING id, ip_address, added, expires, reason, added_by_user_id, revoked_at, revoked_by_user_id, revocation_reason
"""

LIST_IP_ACTIVITY: typing.Final[typing.LiteralString] = """-- name: ListIpActivity :many
SELECT
    event_at,
    event_type,
    COALESCE(target_id, 0)::BIGINT AS target_id,
    COALESCE(target_slug, '')::TEXT AS target_slug,
    details
FROM (
    -- 1. General Telemetry Hits (Path probes across routers)
    SELECT
        th.occurred_at AS event_at,
        ('hit_' || th.router_group)::TEXT AS event_type,
        NULL::BIGINT AS target_id,
        th.path::TEXT AS target_slug,
        ('status=' || th.status_code::text || ' | method=' || th.method)::TEXT AS details
    FROM telemetry_hits th
    WHERE th.ip_address = %(p1)s::inet

    UNION ALL

    -- 2. Credential Stuffing / Login Probes
    SELECT
        csa.attempted_at AS event_at,
        CASE WHEN csa.was_fake_success THEN 'credential_stuffing_fake_success' ELSE 'credential_stuffing' END::TEXT AS event_type,
        NULL::BIGINT AS target_id,
        csa.endpoint_path::TEXT AS target_slug,
        ('username=' || csa.username || ' | password=' || csa.password)::TEXT AS details
    FROM credential_stuffing_attempts csa
    WHERE csa.ip_address = %(p1)s::inet

    UNION ALL

    -- 3. Decoy Views / Downloads
    SELECT
        dv.viewed_at AS event_at,
        CASE WHEN d.type = 'binary' THEN 'decoy_downloaded' ELSE 'decoy_viewed' END::TEXT AS event_type,
        d.id::BIGINT AS target_id,
        d.slug::TEXT AS target_slug,
        NULL::TEXT AS details
    FROM decoy_views dv
    INNER JOIN decoys d ON d.id = dv.decoy_id
    WHERE dv.ip_address = %(p1)s::inet

    UNION ALL

    -- 4. Decoy Password Attempts
    SELECT
        dpa.attempted_at AS event_at,
        CASE WHEN dpa.successful THEN 'decoy_password_success' ELSE 'decoy_password_failure' END::TEXT AS event_type,
        d.id::BIGINT AS target_id,
        d.slug::TEXT AS target_slug,
        NULL::TEXT AS details
    FROM decoy_password_attempts dpa
    INNER JOIN decoys d ON d.id = dpa.decoy_id
    WHERE dpa.ip_address = %(p1)s::inet

    UNION ALL

    -- 5. IP Ban Actions
    SELECT
        b.added AS event_at,
        'ip_banned'::TEXT AS event_type,
        NULL::BIGINT AS target_id,
        NULL::TEXT AS target_slug,
        ('by_user_id=' || b.added_by_user_id::text || COALESCE(' | reason=' || NULLIF(b.reason, ''), ''))::TEXT AS details
    FROM ip_bans b
    WHERE b.ip_address = %(p1)s::inet

    UNION ALL

    -- 6. IP Ban Revocations
    SELECT
        b.revoked_at AS event_at,
        'ip_ban_revoked'::TEXT AS event_type,
        NULL::BIGINT AS target_id,
        NULL::TEXT AS target_slug,
        ('by_user_id=' || b.revoked_by_user_id::text)::TEXT AS details
    FROM ip_bans b
    WHERE b.ip_address = %(p1)s::inet
) events
WHERE event_at IS NOT NULL
ORDER BY event_at DESC
LIMIT %(p3)s::int
OFFSET %(p2)s::int
"""


class QueryResults[T]:
    __slots__ = ("_conn", "_cursor", "_decode_hook", "_iterator", "_params", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: typing.LiteralString,
        decode_hook: collections.abc.Callable[[psycopg.rows.TupleRow], T],
        params: dict[str, QueryResultsArgsType] | None = None,
    ) -> None:
        self._conn = conn
        self._sql: typing.LiteralString = sql
        self._decode_hook = decode_hook
        self._params = params
        self._cursor: psycopg.AsyncCursor[psycopg.rows.TupleRow] | None = None
        self._iterator: collections.abc.AsyncIterator[psycopg.rows.TupleRow] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await (await self._conn.execute(self._sql, self._params)).fetchall()
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = await self._conn.execute(self._sql, self._params)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def upsert_user(conn: ConnectionLike, *, google_sub: str, email: str, name: str, is_admin: bool) -> models.User | None:
    row = await (await conn.execute(UPSERT_USER, {"p1": google_sub, "p2": email, "p3": name, "p4": is_admin})).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], google_sub=row[1], email=row[2], name=row[3], created=row[4], last_login=row[5], is_admin=row[6])


async def get_user_by_session_token_hash(conn: ConnectionLike, *, token_hash: str) -> models.User | None:
    row = await (await conn.execute(GET_USER_BY_SESSION_TOKEN_HASH, {"p1": token_hash})).fetchone()
    if row is None:
        return None
    return models.User(id_=row[0], google_sub=row[1], email=row[2], name=row[3], created=row[4], last_login=row[5], is_admin=row[6])


async def create_telemetry_hit(conn: ConnectionLike, *, ip_address: str, method: str, path: str, router_group: str, user_agent: str | None, headers: str, status_code: int) -> None:
    await conn.execute(CREATE_TELEMETRY_HIT, {"p1": ip_address, "p2": method, "p3": path, "p4": router_group, "p5": user_agent, "p6": headers, "p7": status_code})


async def create_credential_stuffing_attempt(conn: ConnectionLike, *, ip_address: str, endpoint_path: str, username: str, password: str, was_fake_success: bool) -> None:
    await conn.execute(CREATE_CREDENTIAL_STUFFING_ATTEMPT, {"p1": ip_address, "p2": endpoint_path, "p3": username, "p4": password, "p5": was_fake_success})


async def get_ip_threat_summary(conn: ConnectionLike, *, ip_address: str) -> GetIpThreatSummaryRow | None:
    row = await (await conn.execute(GET_IP_THREAT_SUMMARY, {"p1": ip_address})).fetchone()
    if row is None:
        return None
    return GetIpThreatSummaryRow(ip_address=str(row[0]), total_requests=row[1], unique_endpoints_probed=row[2], last_seen_at=row[3])


async def create_active_ip_ban(conn: ConnectionLike, *, ip_address: str, expires: datetime.datetime | None, reason: str | None, added_by_user_id: int) -> models.IpBan | None:
    row = await (await conn.execute(CREATE_ACTIVE_IP_BAN, {"p1": ip_address, "p2": expires, "p3": reason, "p4": added_by_user_id})).fetchone()
    if row is None:
        return None
    return models.IpBan(id_=row[0], ip_address=str(row[1]), added=row[2], expires=row[3], reason=row[4], added_by_user_id=row[5], revoked_at=row[6], revoked_by_user_id=row[7], revocation_reason=row[8])


def list_ip_activity(conn: ConnectionLike, *, ip_address: str, offset: int, limit: int) -> QueryResults[ListIpActivityRow]:
    def _decode_hook(row: psycopg.rows.TupleRow) -> ListIpActivityRow:
        return ListIpActivityRow(event_at=row[0], event_type=row[1], target_id=row[2], target_slug=row[3], details=row[4])

    return QueryResults(conn, LIST_IP_ACTIVITY, _decode_hook, {"p1": ip_address, "p2": offset, "p3": limit})
