/**
 * List magic-string candidates in the hand-written TypeScript and Svelte code: the web twin of
 * api/scripts/find_magic_strings.py.
 *
 * Run from `web/`: `node scripts/find-magic-strings.ts [paths...]` (default: `src` and `scripts`).
 *
 * Reports string literals that are either
 *   - repeated: the same value appears more than once across the scanned files, or
 *   - used as a key or a compared value: `===`/`!==`/`==`/`!=`/`in` operands, `case` labels,
 *     element-access keys, and `.get()`/`.getAll()`/`.has()`/`.set()`/`.delete()` keys,
 * together with each occurrence's location and role. It is a candidate list, not a verdict: judge
 * each finding with the `magic-strings` skill. Only a .svelte file's <script> blocks are scanned
 * (markup text is copy, not code). Imports, type-level literals and template-literal fragments are
 * skipped, and so is the generated API client. Always exits 0: a review list, not a gate.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { parse } from 'svelte/compiler';
import ts from 'typescript';

const SRC_DIR = 'src';
const DEFAULT_PATHS = [SRC_DIR, 'scripts'];
// Generated by @hey-api/openapi-ts: change the API and regenerate instead.
const GENERATED_DIR = path.join(SRC_DIR, 'lib', 'client');
const ENCODING = 'utf8';
const TS_EXTENSION = '.ts';
const SVELTE_EXTENSION = '.svelte';
const SCRIPT_CLOSE_TAG = '</script';
const KEY_METHODS = new Set(['get', 'getAll', 'has', 'set', 'delete']);
const COMPARISONS = new Set([
	ts.SyntaxKind.EqualsEqualsEqualsToken,
	ts.SyntaxKind.ExclamationEqualsEqualsToken,
	ts.SyntaxKind.EqualsEqualsToken,
	ts.SyntaxKind.ExclamationEqualsToken,
	ts.SyntaxKind.InKeyword
]);

const Role = {
	COMPARED: 'compared',
	PATTERN: 'case label',
	KEY: 'key',
	OTHER: 'value'
} as const;
type Role = (typeof Role)[keyof typeof Role];

interface Occurrence {
	file: string;
	line: number;
	role: Role;
}

/** A piece of TypeScript to scan, and the line of its file it starts on. */
interface Source {
	file: string;
	code: string;
	firstLine: number;
}

function sourceFiles(root: string): string[] {
	if (statSync(root).isFile()) {
		return [root];
	}
	return readdirSync(root, { recursive: true, encoding: ENCODING })
		.map((entry) => path.join(root, entry))
		.filter((file) => !file.startsWith(GENERATED_DIR))
		.filter((file) => file.endsWith(TS_EXTENSION) || file.endsWith(SVELTE_EXTENSION))
		.sort();
}

function lineAt(text: string, offset: number): number {
	return text.slice(0, offset).split('\n').length;
}

/** A .ts file whole, or each <script> block of a .svelte file. */
function sources(file: string): Source[] {
	const text = readFileSync(file, ENCODING);
	if (!file.endsWith(SVELTE_EXTENSION)) {
		return [{ file, code: text, firstLine: 1 }];
	}
	const ast = parse(text, { modern: true });
	return [ast.module, ast.instance].flatMap((script) => {
		// Typed `Script | null`, but a missing block is left undefined at runtime.
		if (!script) {
			return [];
		}
		const start = text.indexOf('>', script.start) + 1;
		const end = text.lastIndexOf(SCRIPT_CLOSE_TAG, script.end);
		return [{ file, code: text.slice(start, end), firstLine: lineAt(text, start) }];
	});
}

function roleOf(node: ts.StringLiteralLike): Role {
	const parent = node.parent;
	if (ts.isBinaryExpression(parent) && COMPARISONS.has(parent.operatorToken.kind)) {
		return Role.COMPARED;
	}
	if (ts.isCaseClause(parent)) {
		return Role.PATTERN;
	}
	if (ts.isElementAccessExpression(parent) && parent.argumentExpression === node) {
		return Role.KEY;
	}
	if (
		ts.isCallExpression(parent) &&
		parent.arguments[0] === node &&
		ts.isPropertyAccessExpression(parent.expression) &&
		KEY_METHODS.has(parent.expression.name.text)
	) {
		return Role.KEY;
	}
	return Role.OTHER;
}

function isSkipped(node: ts.StringLiteralLike): boolean {
	const parent = node.parent;
	return (
		ts.isImportDeclaration(parent) ||
		ts.isExportDeclaration(parent) ||
		ts.isExternalModuleReference(parent) ||
		ts.isImportTypeNode(parent.parent) ||
		ts.isLiteralTypeNode(parent)
	);
}

function collect({ file, code, firstLine }: Source): [string, Occurrence][] {
	const tree = ts.createSourceFile(file, code, ts.ScriptTarget.Latest, true);
	const found: [string, Occurrence][] = [];
	const visit = (node: ts.Node): void => {
		if (ts.isStringLiteralLike(node) && !isSkipped(node)) {
			const { line } = tree.getLineAndCharacterOfPosition(node.getStart(tree));
			found.push([node.text, { file, line: firstLine + line, role: roleOf(node) }]);
		}
		ts.forEachChild(node, visit);
	};
	visit(tree);
	return found;
}

const { positionals } = parseArgs({ allowPositionals: true });
const roots = positionals.length > 0 ? positionals : DEFAULT_PATHS;
const occurrences = new Map<string, Occurrence[]>();
for (const source of roots.flatMap(sourceFiles).flatMap(sources)) {
	for (const [value, occurrence] of collect(source)) {
		occurrences.set(value, [...(occurrences.get(value) ?? []), occurrence]);
	}
}

const candidates = [...occurrences].filter(
	([, found]) => found.length > 1 || found.some((o) => o.role !== Role.OTHER)
);
candidates.sort(([, a], [, b]) => b.length - a.length);
for (const [value, found] of candidates) {
	console.log(`${JSON.stringify(value)}  x${String(found.length)}`);
	for (const o of found) {
		console.log(`    ${o.file}:${String(o.line)}  ${o.role}`);
	}
}
console.log(`\n${String(candidates.length)} candidate string(s)`);
