/**
 * Generate the world map's land outline, `src/lib/world.gen.ts`, from Natural Earth's 1:110m land
 * polygons (public domain), at a pinned release.
 *
 * Run from `web/`: `npm run gen-map`. It only needs running again to change the source or the
 * precision; the output is committed, so building the site never touches the network.
 *
 * The projection is equirectangular, the simplest there is: a point at (longitude, latitude) is
 * drawn at x = longitude, y = -latitude (SVG's y grows downwards), so the WorldMap component can
 * place an address's point without any projection code.
 */

import { writeFileSync } from 'node:fs';

const SOURCE =
	'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_110m_land.geojson';
const OUTPUT = 'src/lib/world.gen.ts';
// A tenth of a degree, about 11 km: finer than the 1:110m data itself.
const DECIMALS = 1;

interface Land {
	features: { geometry: { type: 'Polygon'; coordinates: [number, number][][] } }[];
}

const response = await fetch(SOURCE);
if (!response.ok) {
	throw new Error(`${SOURCE}: HTTP ${String(response.status)}`);
}
const land = (await response.json()) as Land;

const coordinate = (value: number) => String(Number(value.toFixed(DECIMALS)));

const path = land.features
	.flatMap((feature) => feature.geometry.coordinates)
	.map(
		(ring) =>
			'M' +
			ring
				.map(([longitude, latitude]) => `${coordinate(longitude)} ${coordinate(-latitude)}`)
				.join('L') +
			'Z'
	)
	.join('');

writeFileSync(
	OUTPUT,
	`// Generated by scripts/gen-world-map.ts from Natural Earth (public domain). Don't edit.\n` +
		`// Land outlines in degrees: x = longitude, y = -latitude.\n` +
		`export const LAND = '${path}';\n`
);
console.log(`Wrote ${OUTPUT}: ${String(path.length)} characters`);
