// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ReportHitData, ReportHitErrors, ReportHitResponses, ReportLoginData, ReportLoginErrors, ReportLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Report Hit
 *
 * Record a request the decoy app served, as a honeypot hit.
 *
 * Written after this response, so the decoy app waits only for the round trip, not the database.
 */
export const reportHit = <ThrowOnError extends boolean = false>(options: Options<ReportHitData, ThrowOnError>): RequestResult<ReportHitResponses, ReportHitErrors, ThrowOnError> => (options.client ?? client).post<ReportHitResponses, ReportHitErrors, ThrowOnError>({
    url: '/ingest/hits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Report Login
 *
 * Record submitted credentials and decide the outcome the decoy app shows.
 */
export const reportLogin = <ThrowOnError extends boolean = false>(options: Options<ReportLoginData, ThrowOnError>): RequestResult<ReportLoginResponses, ReportLoginErrors, ThrowOnError> => (options.client ?? client).post<ReportLoginResponses, ReportLoginErrors, ThrowOnError>({
    url: '/ingest/logins',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
