// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Canary
 *
 * The secret to put in it: fresh, random, and recorded against the visitor.
 */
export type Canary = {
    /**
     * Secret
     */
    secret: string;
};

/**
 * CanaryRequest
 *
 * A leaked file the decoy is about to serve.
 */
export type CanaryRequest = {
    /**
     * Path
     */
    path: string;
};

/**
 * DecoyHit
 *
 * One request the decoy app served: exactly what the visitor sent, and the status it got.
 */
export type DecoyHit = {
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Query
     */
    query: string | null;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body: string | null;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Banned
     */
    banned: boolean;
    /**
     * Rule Id
     */
    rule_id: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InstallAttempt
 *
 * A WordPress install the decoy app's installer accepted: the site and administrator account
 * the visitor chose, as submitted. The installer has already checked them as WordPress does.
 */
export type InstallAttempt = {
    /**
     * Path
     */
    path: string;
    /**
     * Site Title
     */
    site_title: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * InstallOutcome
 *
 * The installed account's password, when WordPress made one up (none was chosen): the
 * installer shows it. Null when the visitor chose their own.
 */
export type InstallOutcome = {
    /**
     * Generated Password
     */
    generated_password: string | null;
};

/**
 * LoginAttempt
 *
 * Credentials a visitor submitted to one of the decoy app's login forms.
 */
export type LoginAttempt = {
    /**
     * Path
     */
    path: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginOutcome
 *
 * How the decoy should answer a login: decided here, not in the decoy app.
 */
export type LoginOutcome = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Known Account
     */
    known_account: boolean;
    /**
     * Delay Ms
     */
    delay_ms: number;
};

/**
 * RenderedResponse
 *
 * What the decoy serves instead of its own page.
 */
export type RenderedResponse = {
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body: string;
    /**
     * Delay Ms
     */
    delay_ms: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Visit
 *
 * A request the decoy app received, as the visitor sent it.
 */
export type Visit = {
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Query
     */
    query: string | null;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
};

/**
 * VisitVerdict
 *
 * How the decoy should answer a request.
 */
export type VisitVerdict = {
    /**
     * Banned
     */
    banned: boolean;
    /**
     * Rule Id
     */
    rule_id: number | null;
    response: RenderedResponse | null;
};

export type JudgeVisitData = {
    body: Visit;
    path?: never;
    query?: never;
    url: '/ingest/visits';
};

export type JudgeVisitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JudgeVisitError = JudgeVisitErrors[keyof JudgeVisitErrors];

export type JudgeVisitResponses = {
    /**
     * Successful Response
     */
    200: VisitVerdict;
};

export type JudgeVisitResponse = JudgeVisitResponses[keyof JudgeVisitResponses];

export type ReportHitData = {
    body: DecoyHit;
    path?: never;
    query?: never;
    url: '/ingest/hits';
};

export type ReportHitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportHitError = ReportHitErrors[keyof ReportHitErrors];

export type ReportHitResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ReportHitResponse = ReportHitResponses[keyof ReportHitResponses];

export type ReportLoginData = {
    body: LoginAttempt;
    path?: never;
    query?: never;
    url: '/ingest/logins';
};

export type ReportLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportLoginError = ReportLoginErrors[keyof ReportLoginErrors];

export type ReportLoginResponses = {
    /**
     * Successful Response
     */
    200: LoginOutcome;
};

export type ReportLoginResponse = ReportLoginResponses[keyof ReportLoginResponses];

export type ReportInstallData = {
    body: InstallAttempt;
    path?: never;
    query?: never;
    url: '/ingest/installs';
};

export type ReportInstallErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReportInstallError = ReportInstallErrors[keyof ReportInstallErrors];

export type ReportInstallResponses = {
    /**
     * Successful Response
     */
    200: InstallOutcome;
};

export type ReportInstallResponse = ReportInstallResponses[keyof ReportInstallResponses];

export type IssueCanaryData = {
    body: CanaryRequest;
    path?: never;
    query?: never;
    url: '/ingest/canaries';
};

export type IssueCanaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssueCanaryError = IssueCanaryErrors[keyof IssueCanaryErrors];

export type IssueCanaryResponses = {
    /**
     * Successful Response
     */
    200: Canary;
};

export type IssueCanaryResponse = IssueCanaryResponses[keyof IssueCanaryResponses];
