// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DecoyHit
 *
 * One request the decoy app served: exactly what the visitor sent, and the status it got.
 */
export type DecoyHit = {
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Query
     */
    query: string | null;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body: string | null;
    /**
     * Status Code
     */
    status_code: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginAttempt
 *
 * Credentials a visitor submitted to one of the decoy app's login forms.
 */
export type LoginAttempt = {
    /**
     * Path
     */
    path: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginOutcome
 *
 * Whether the decoy should treat the login as successful: decided here, not in the decoy app.
 */
export type LoginOutcome = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * Message
 */
export type Message = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HitsRecordDecoyHitData = {
    body: DecoyHit;
    path?: never;
    query?: never;
    url: '/ingest/hits';
};

export type HitsRecordDecoyHitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type HitsRecordDecoyHitError = HitsRecordDecoyHitErrors[keyof HitsRecordDecoyHitErrors];

export type HitsRecordDecoyHitResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type HitsRecordDecoyHitResponse = HitsRecordDecoyHitResponses[keyof HitsRecordDecoyHitResponses];

export type LoginsAttemptLoginData = {
    body: LoginAttempt;
    path?: never;
    query?: never;
    url: '/ingest/logins';
};

export type LoginsAttemptLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type LoginsAttemptLoginError = LoginsAttemptLoginErrors[keyof LoginsAttemptLoginErrors];

export type LoginsAttemptLoginResponses = {
    /**
     * Successful Response
     */
    200: LoginOutcome;
};

export type LoginsAttemptLoginResponse = LoginsAttemptLoginResponses[keyof LoginsAttemptLoginResponses];
