import prettier from 'eslint-config-prettier';
import path from 'node:path';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

// Ways of calling the API without the generated client, which `apiOptions(event)` configures.
const API_BY_HAND = [
	// fetch(...), globalThis.fetch(...), event.fetch(...)
	"CallExpression[callee.name='fetch']",
	"CallExpression[callee.property.name='fetch']",
	// Other hand-rolled HTTP.
	'NewExpression[callee.name=/^(XMLHttpRequest|EventSource|WebSocket|Request)$/]',
	// An API path written out: '/ingest/...' or `/ingest/${...}`.
	'Literal[value=/^\\/ingest(\\/|$)/]',
	'TemplateElement[value.raw=/^\\/ingest(\\/|$)/]',
	// The client's internals (client.get({ url }), createClient): use the generated SDK functions.
	'ImportDeclaration[source.value=/^\\$lib\\/client\\/(client|core)/]'
];

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// Generated by @hey-api/openapi-ts (npm run generate:api).
	{ ignores: ['src/lib/client/'] },
	js.configs.recommended,
	// The TypeScript analog of basedpyright's strictest mode: type-aware and strict.
	ts.configs.strictTypeChecked,
	ts.configs.stylisticTypeChecked,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node },
			parserOptions: {
				// openapi-ts.config.ts sits outside SvelteKit's generated tsconfig.
				projectService: { allowDefaultProject: ['openapi-ts.config.ts'] },
				tsconfigRootDir: import.meta.dirname
			}
		},
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		// The API client is generated (src/lib/client, ignored above): never call the API by hand.
		// See .claude/skills/generated-api-client.
		files: ['src/**'],
		rules: {
			'no-restricted-syntax': [
				'error',
				...API_BY_HAND.map((selector) => ({
					selector,
					message:
						'Call the API through the generated client ($lib/client) with apiOptions(event), ' +
						'not by hand. See decoy/README.md.'
				}))
			]
		}
	},
	{
		// No magic numbers: name them, or use a library's constant (HTTP statuses: node:http2).
		rules: {
			'no-magic-numbers': 'off',
			'@typescript-eslint/no-magic-numbers': [
				'error',
				{
					ignore: [-1, 0, 1],
					ignoreEnums: true,
					ignoreNumericLiteralTypes: true,
					ignoreReadonlyClassProperties: true,
					ignoreTypeIndexes: true
				}
			]
		}
	},
	// Plain JavaScript (config files) has no types for the type-aware rules to use.
	{ files: ['**/*.js'], extends: [ts.configs.disableTypeChecked] },
	{
		// Override or add rule settings here, such as:
		// 'svelte/button-has-type': 'error'
		rules: {}
	}
);
