"""List magic-string candidates in the hand-written Python code.

Run from `api/`: `uv run python scripts/find_magic_strings.py [paths...]` (default: `src` and `scripts`).

Reports string literals that are either
  * repeated: the same value appears more than once across the scanned files, or
  * used as a key or a compared value: `==`/`!=`/`in` operands, `match` patterns, subscript keys,
    and `.get()`/`.pop()`/`.setdefault()` keys,
together with each occurrence's location and role. It is a candidate list, not a verdict: judge
each finding with the `magic-strings` skill. Docstrings, f-string fragments, and generated sqlc
modules are skipped. Exits 1 when there are candidates, so it can gate a checklist.
"""

import ast
import sys
from collections import defaultdict
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import override

DEFAULT_PATHS = ("src", "scripts")
# Generated by sqlc: fix their SQL sources instead (see .claude/rules/database.md).
GENERATED = frozenset(
    {
        Path("src/attenborough/db/__init__.py"),
        Path("src/attenborough/db/enums.py"),
        Path("src/attenborough/db/models.py"),
        Path("src/attenborough/db/queries.py"),
    }
)
KEY_METHODS = frozenset({"get", "pop", "setdefault"})


class Role(StrEnum):
    COMPARED = "compared"
    PATTERN = "match pattern"
    KEY = "key"
    OTHER = "value"


@dataclass(frozen=True)
class Occurrence:
    path: Path
    line: int
    role: Role


class Collector(ast.NodeVisitor):
    def __init__(self, path: Path) -> None:
        self.path: Path = path
        self.found: list[tuple[str, Occurrence]] = []
        self._roles: dict[int, Role] = {}
        self._skip: set[int] = set()
        # Decorator calls such as `@router.get("/path")` are route declarations, not dict lookups.
        self._decorators: set[int] = set()

    def _mark(self, node: ast.AST | None, role: Role) -> None:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            self._roles[id(node)] = role

    def _skip_docstring(self, body: list[ast.stmt]) -> None:
        match body:
            case [ast.Expr(value=ast.Constant(value=str()) as doc), *_]:
                self._skip.add(id(doc))
            case _:
                pass

    @override
    def visit_Module(self, node: ast.Module) -> None:
        self._skip_docstring(node.body)
        self.generic_visit(node)

    @override
    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        self._skip_docstring(node.body)
        self.generic_visit(node)

    @override
    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._skip_docstring(node.body)
        self._decorators.update(id(d) for d in node.decorator_list)
        self.generic_visit(node)

    @override
    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self._skip_docstring(node.body)
        self._decorators.update(id(d) for d in node.decorator_list)
        self.generic_visit(node)

    @override
    def visit_JoinedStr(self, node: ast.JoinedStr) -> None:
        # Literal fragments of f-strings are formatting, not values.
        for part in node.values:
            self._skip.add(id(part))
        self.generic_visit(node)

    @override
    def visit_Compare(self, node: ast.Compare) -> None:
        for operand in (node.left, *node.comparators):
            self._mark(operand, Role.COMPARED)
            if isinstance(operand, ast.Tuple | ast.List | ast.Set):
                for element in operand.elts:
                    self._mark(element, Role.COMPARED)
        self.generic_visit(node)

    @override
    def visit_MatchValue(self, node: ast.MatchValue) -> None:
        self._mark(node.value, Role.PATTERN)
        self.generic_visit(node)

    @override
    def visit_MatchMapping(self, node: ast.MatchMapping) -> None:
        for key in node.keys:
            self._mark(key, Role.PATTERN)
        self.generic_visit(node)

    @override
    def visit_Subscript(self, node: ast.Subscript) -> None:
        self._mark(node.slice, Role.KEY)
        self.generic_visit(node)

    @override
    def visit_Call(self, node: ast.Call) -> None:
        if (
            isinstance(node.func, ast.Attribute)
            and node.func.attr in KEY_METHODS
            and node.args
            and id(node) not in self._decorators
        ):
            self._mark(node.args[0], Role.KEY)
        self.generic_visit(node)

    @override
    def visit_Constant(self, node: ast.Constant) -> None:
        if isinstance(node.value, str) and id(node) not in self._skip:
            role = self._roles.get(id(node), Role.OTHER)
            self.found.append((node.value, Occurrence(self.path, node.lineno, role)))


def python_files(paths: list[str]) -> list[Path]:
    files: list[Path] = []
    for raw in paths:
        path = Path(raw)
        candidates = sorted(path.rglob("*.py")) if path.is_dir() else [path]
        files.extend(p for p in candidates if p not in GENERATED)
    return files


def main() -> int:
    paths = sys.argv[1:] or list(DEFAULT_PATHS)
    occurrences: defaultdict[str, list[Occurrence]] = defaultdict(list)
    for file in python_files(paths):
        collector = Collector(file)
        collector.visit(ast.parse(file.read_text(), filename=str(file)))
        for value, occurrence in collector.found:
            occurrences[value].append(occurrence)

    candidates = {
        value: found
        for value, found in occurrences.items()
        if len(found) > 1 or any(o.role is not Role.OTHER for o in found)
    }
    for value, found in sorted(candidates.items(), key=lambda item: -len(item[1])):
        print(f"{value!r:.70}  x{len(found)}")
        for o in found:
            print(f"    {o.path}:{o.line}  {o.role}")
    print(f"\n{len(candidates)} candidate string(s)")
    return 1 if candidates else 0


if __name__ == "__main__":
    sys.exit(main())
