"""Fill the development database with synthetic honeypot traffic, to measure the exhibit at volume.

Run from `api/`, naming the database to confirm it (it must be the one in `api/.env`):

    uv run python scripts/seed_db.py --database attenborough_dev

The defaults add two million hits over the last 90 days, in time order as real traffic arrives:
half from one busy address, the first of 198.18.0.0/15 (reserved for benchmarking, so no real
address is implicated), the rest from thirty thousand addresses in that range, and login attempts
at 5% of hits. The rows are generated by the database itself (`SeedHits` and `SeedLoginAttempts` in
queries.sql), in batches. Never run it against a database whose data you keep: remove seeded data
by resetting (`scripts/reset_db.py --yes`).
"""

import argparse
import asyncio
import sys
import time

from attenborough import settings
from attenborough.db import queries
from attenborough.db.ops import db_conn_pool

# 198.18.0.0/15: RFC 2544's benchmarking range, never a real visitor.
FIRST_ADDRESS = "198.18.0.0"
BATCH = 100_000
DAYS = 90
LOGIN_SHARE = 0.05


class Args(argparse.Namespace):
    database: str = ""
    hits: int = 2_000_000
    addresses: int = 30_000
    busy_share: float = 0.5


async def seed(args: Args) -> None:
    logins = round(args.hits * LOGIN_SHARE)
    async with db_conn_pool, db_conn_pool.connection() as conn:
        for start in range(0, args.hits, BATCH):
            count = min(BATCH, args.hits - start)
            started = time.monotonic()
            await queries.seed_hits(
                conn,
                first_address=FIRST_ADDRESS,
                busy_share=args.busy_share,
                addresses=args.addresses,
                days=DAYS,
                total=args.hits,
                start=start,
                count=count,
            )
            # The login attempts of the same stretch of time.
            await queries.seed_login_attempts(
                conn,
                first_address=FIRST_ADDRESS,
                busy_share=args.busy_share,
                addresses=args.addresses,
                days=DAYS,
                total=logins,
                start=round(start * LOGIN_SHARE),
                count=round((start + count) * LOGIN_SHARE) - round(start * LOGIN_SHARE),
            )
            print(
                f"{start + count:>10,} of {args.hits:,} hits ({time.monotonic() - started:.1f} s)"
            )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    _ = parser.add_argument(
        "--database",
        required=True,
        help="the configured database's name (DB_DATABASE), to confirm which one is filled",
    )
    _ = parser.add_argument("--hits", type=int, default=Args.hits)
    _ = parser.add_argument("--addresses", type=int, default=Args.addresses)
    _ = parser.add_argument(
        "--busy-share",
        type=float,
        default=Args.busy_share,
        help="the share of hits from the one busy address",
    )
    args = parser.parse_args(namespace=Args())
    if args.database != settings.DB_DATABASE:
        parser.error(
            f"--database {args.database!r} is not the configured database ({settings.DB_DATABASE!r})"
        )
    asyncio.run(seed(args))
    return 0


if __name__ == "__main__":
    sys.exit(main())
