// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHitData, GetHitErrors, GetHitResponses, GetIpEventsData, GetIpEventsErrors, GetIpEventsResponses, GetIpSummaryData, GetIpSummaryErrors, GetIpSummaryResponses, GetPatternsData, GetPatternsResponses, GetTakeoverData, GetTakeoverErrors, GetTakeoverResponses, ListRecentEventsData, ListRecentEventsErrors, ListRecentEventsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Recent Events
 *
 * The latest visitor events from every IP address, newest first.
 */
export const listRecentEvents = <ThrowOnError extends boolean = false>(options?: Options<ListRecentEventsData, ThrowOnError>): RequestResult<ListRecentEventsResponses, ListRecentEventsErrors, ThrowOnError> => (options?.client ?? client).get<ListRecentEventsResponses, ListRecentEventsErrors, ThrowOnError>({ url: '/exhibit/feed', ...options });

/**
 * Get Ip Events
 *
 * Everything one IP address did, newest first.
 */
export const getIpEvents = <ThrowOnError extends boolean = false>(options: Options<GetIpEventsData, ThrowOnError>): RequestResult<GetIpEventsResponses, GetIpEventsErrors, ThrowOnError> => (options.client ?? client).get<GetIpEventsResponses, GetIpEventsErrors, ThrowOnError>({ url: '/exhibit/ip/{ip_addr}/activity', ...options });

/**
 * Get Ip Summary
 *
 * What one IP address did, in numbers, and where it is.
 */
export const getIpSummary = <ThrowOnError extends boolean = false>(options: Options<GetIpSummaryData, ThrowOnError>): RequestResult<GetIpSummaryResponses, GetIpSummaryErrors, ThrowOnError> => (options.client ?? client).get<GetIpSummaryResponses, GetIpSummaryErrors, ThrowOnError>({ url: '/exhibit/ip/{ip_addr}/summary', ...options });

/**
 * Get Hit
 *
 * One request to the honeypot in full: its headers and its whole stored body. 404 for any
 * other request, such as the exhibit's own.
 */
export const getHit = <ThrowOnError extends boolean = false>(options: Options<GetHitData, ThrowOnError>): RequestResult<GetHitResponses, GetHitErrors, ThrowOnError> => (options.client ?? client).get<GetHitResponses, GetHitErrors, ThrowOnError>({ url: '/exhibit/hits/{hit_id}', ...options });

/**
 * Get Takeover
 *
 * One install through the decoy's installer, and every login into the account it created,
 * from whichever addresses, oldest first.
 */
export const getTakeover = <ThrowOnError extends boolean = false>(options: Options<GetTakeoverData, ThrowOnError>): RequestResult<GetTakeoverResponses, GetTakeoverErrors, ThrowOnError> => (options.client ?? client).get<GetTakeoverResponses, GetTakeoverErrors, ThrowOnError>({ url: '/exhibit/installs/{install_id}', ...options });

/**
 * Get Patterns
 *
 * What visitors are after, who they are, when they come, and their tools and wordlists, in
 * aggregate. Recomputed at most every few minutes (patterns.py).
 */
export const getPatterns = <ThrowOnError extends boolean = false>(options?: Options<GetPatternsData, ThrowOnError>): RequestResult<GetPatternsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetPatternsResponses, unknown, ThrowOnError>({ url: '/exhibit/patterns', ...options });
