// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { FeedListRecentData, FeedListRecentErrors, FeedListRecentResponses, IpGetIpActivityData, IpGetIpActivityErrors, IpGetIpActivityResponses, MetaGetMetaData, MetaGetMetaErrors, MetaGetMetaResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Recent
 *
 * The latest visitor activity from every IP address, newest first.
 */
export const feedListRecent = <ThrowOnError extends boolean = false>(options?: Options<FeedListRecentData, ThrowOnError>): RequestResult<FeedListRecentResponses, FeedListRecentErrors, ThrowOnError> => (options?.client ?? client).get<FeedListRecentResponses, FeedListRecentErrors, ThrowOnError>({ url: '/exhibit/feed', ...options });

/**
 * Get Ip Activity
 */
export const ipGetIpActivity = <ThrowOnError extends boolean = false>(options: Options<IpGetIpActivityData, ThrowOnError>): RequestResult<IpGetIpActivityResponses, IpGetIpActivityErrors, ThrowOnError> => (options.client ?? client).get<IpGetIpActivityResponses, IpGetIpActivityErrors, ThrowOnError>({ url: '/exhibit/ip/{ip_addr}/activity', ...options });

/**
 * Get Meta
 */
export const metaGetMeta = <ThrowOnError extends boolean = false>(options?: Options<MetaGetMetaData, ThrowOnError>): RequestResult<MetaGetMetaResponses, MetaGetMetaErrors, ThrowOnError> => (options?.client ?? client).get<MetaGetMetaResponses, MetaGetMetaErrors, ThrowOnError>({ url: '/exhibit/meta', ...options });
