// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { BanIpData, BanIpErrors, BanIpResponses, CreateRuleData, CreateRuleErrors, CreateRuleResponses, FinishGoogleLoginData, FinishGoogleLoginErrors, FinishGoogleLoginResponses, GetHitData, GetHitErrors, GetHitResponses, GetIpEventsData, GetIpEventsErrors, GetIpEventsResponses, GetIpSummaryData, GetIpSummaryErrors, GetIpSummaryResponses, GetMeData, GetMeResponses, GetPatternsData, GetPatternsResponses, GetRuleData, GetRuleErrors, GetRuleResponses, GetTakeoverData, GetTakeoverErrors, GetTakeoverResponses, ListActiveBansData, ListActiveBansResponses, ListAuditLogData, ListAuditLogResponses, ListIpBansData, ListIpBansErrors, ListIpBansResponses, ListRecentEventsData, ListRecentEventsErrors, ListRecentEventsResponses, ListRuleMarkersData, ListRuleMarkersResponses, ListRulesData, ListRulesResponses, LogOutData, LogOutResponses, MoveRuleData, MoveRuleErrors, MoveRuleResponses, PreviewRuleData, PreviewRuleErrors, PreviewRuleResponses, RemoveRuleData, RemoveRuleErrors, RemoveRuleResponses, RevokeBanData, RevokeBanErrors, RevokeBanResponses, StartGoogleLoginData, StartGoogleLoginResponses, UpdateRuleData, UpdateRuleErrors, UpdateRuleResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Recent Events
 *
 * The latest visitor events from every IP address, newest first.
 */
export const listRecentEvents = <ThrowOnError extends boolean = false>(options?: Options<ListRecentEventsData, ThrowOnError>): RequestResult<ListRecentEventsResponses, ListRecentEventsErrors, ThrowOnError> => (options?.client ?? client).get<ListRecentEventsResponses, ListRecentEventsErrors, ThrowOnError>({ url: '/exhibit/feed', ...options });

/**
 * Get Ip Events
 *
 * Everything one IP address did, newest first.
 */
export const getIpEvents = <ThrowOnError extends boolean = false>(options: Options<GetIpEventsData, ThrowOnError>): RequestResult<GetIpEventsResponses, GetIpEventsErrors, ThrowOnError> => (options.client ?? client).get<GetIpEventsResponses, GetIpEventsErrors, ThrowOnError>({ url: '/exhibit/ip/{ip_addr}/activity', ...options });

/**
 * Get Ip Summary
 *
 * What one IP address did, in numbers, where it is, and whether it is banned.
 */
export const getIpSummary = <ThrowOnError extends boolean = false>(options: Options<GetIpSummaryData, ThrowOnError>): RequestResult<GetIpSummaryResponses, GetIpSummaryErrors, ThrowOnError> => (options.client ?? client).get<GetIpSummaryResponses, GetIpSummaryErrors, ThrowOnError>({ url: '/exhibit/ip/{ip_addr}/summary', ...options });

/**
 * Get Hit
 *
 * One request to the honeypot in full: its headers and its whole stored body. 404 for any
 * other request, such as the exhibit's own.
 */
export const getHit = <ThrowOnError extends boolean = false>(options: Options<GetHitData, ThrowOnError>): RequestResult<GetHitResponses, GetHitErrors, ThrowOnError> => (options.client ?? client).get<GetHitResponses, GetHitErrors, ThrowOnError>({ url: '/exhibit/hits/{hit_id}', ...options });

/**
 * Get Takeover
 *
 * One install through the decoy's installer, and every login into the account it created,
 * from whichever addresses, oldest first.
 */
export const getTakeover = <ThrowOnError extends boolean = false>(options: Options<GetTakeoverData, ThrowOnError>): RequestResult<GetTakeoverResponses, GetTakeoverErrors, ThrowOnError> => (options.client ?? client).get<GetTakeoverResponses, GetTakeoverErrors, ThrowOnError>({ url: '/exhibit/installs/{install_id}', ...options });

/**
 * Get Patterns
 *
 * What visitors are after, who they are, when they come, and their tools and wordlists, in
 * aggregate. Recomputed at most every few minutes (patterns.py).
 */
export const getPatterns = <ThrowOnError extends boolean = false>(options?: Options<GetPatternsData, ThrowOnError>): RequestResult<GetPatternsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetPatternsResponses, unknown, ThrowOnError>({ url: '/exhibit/patterns', ...options });

/**
 * Start Google Login
 *
 * Where to send the admin: Google's consent screen, with a fresh state and PKCE challenge.
 */
export const startGoogleLogin = <ThrowOnError extends boolean = false>(options?: Options<StartGoogleLoginData, ThrowOnError>): RequestResult<StartGoogleLoginResponses, unknown, ThrowOnError> => (options?.client ?? client).get<StartGoogleLoginResponses, unknown, ThrowOnError>({ url: '/auth/google', ...options });

/**
 * Finish Google Login
 *
 * Finish a login: a session for a verified ADMIN_EMAILS account, a 404 for anything else.
 * The state is used up whatever happens, so the same callback never works twice.
 */
export const finishGoogleLogin = <ThrowOnError extends boolean = false>(options: Options<FinishGoogleLoginData, ThrowOnError>): RequestResult<FinishGoogleLoginResponses, FinishGoogleLoginErrors, ThrowOnError> => (options.client ?? client).post<FinishGoogleLoginResponses, FinishGoogleLoginErrors, ThrowOnError>({
    url: '/auth/google/callback',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Me
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});

/**
 * Log Out
 *
 * End this session.
 */
export const logOut = <ThrowOnError extends boolean = false>(options?: Options<LogOutData, ThrowOnError>): RequestResult<LogOutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogOutResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * List Active Bans
 *
 * Every active ban, newest first.
 */
export const listActiveBans = <ThrowOnError extends boolean = false>(options?: Options<ListActiveBansData, ThrowOnError>): RequestResult<ListActiveBansResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListActiveBansResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/bans',
    ...options
});

/**
 * List Ip Bans
 *
 * Every ban an address has had, newest first.
 */
export const listIpBans = <ThrowOnError extends boolean = false>(options: Options<ListIpBansData, ThrowOnError>): RequestResult<ListIpBansResponses, ListIpBansErrors, ThrowOnError> => (options.client ?? client).get<ListIpBansResponses, ListIpBansErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/ip/{ip_addr}/bans',
    ...options
});

/**
 * Ban Ip
 *
 * Ban an address: the decoy refuses it from now on (ingest.py, judge_visit). 409 if it is
 * already banned.
 */
export const banIp = <ThrowOnError extends boolean = false>(options: Options<BanIpData, ThrowOnError>): RequestResult<BanIpResponses, BanIpErrors, ThrowOnError> => (options.client ?? client).post<BanIpResponses, BanIpErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/ip/{ip_addr}/bans',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke Ban
 *
 * End an active ban now. 404 if there is no active ban with that id.
 */
export const revokeBan = <ThrowOnError extends boolean = false>(options: Options<RevokeBanData, ThrowOnError>): RequestResult<RevokeBanResponses, RevokeBanErrors, ThrowOnError> => (options.client ?? client).post<RevokeBanResponses, RevokeBanErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/bans/{ban_id}/revoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Audit Log
 *
 * The latest admin actions, newest first.
 */
export const listAuditLog = <ThrowOnError extends boolean = false>(options?: Options<ListAuditLogData, ThrowOnError>): RequestResult<ListAuditLogResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAuditLogResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/audit',
    ...options
});

/**
 * List Rules
 *
 * Every rule, in the order they are tried.
 */
export const listRules = <ThrowOnError extends boolean = false>(options?: Options<ListRulesData, ThrowOnError>): RequestResult<ListRulesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListRulesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules',
    ...options
});

/**
 * Create Rule
 *
 * A new rule, tried after every existing one.
 */
export const createRule = <ThrowOnError extends boolean = false>(options: Options<CreateRuleData, ThrowOnError>): RequestResult<CreateRuleResponses, CreateRuleErrors, ThrowOnError> => (options.client ?? client).post<CreateRuleResponses, CreateRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Rule Markers
 *
 * What a rule's templates can use.
 */
export const listRuleMarkers = <ThrowOnError extends boolean = false>(options?: Options<ListRuleMarkersData, ThrowOnError>): RequestResult<ListRuleMarkersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListRuleMarkersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules/markers',
    ...options
});

/**
 * Preview Rule
 *
 * What a rule (saved or not) would answer a request from an address, using everything the
 * honeypot knows about that address. Issues no canary and records nothing.
 */
export const previewRule = <ThrowOnError extends boolean = false>(options: Options<PreviewRuleData, ThrowOnError>): RequestResult<PreviewRuleResponses, PreviewRuleErrors, ThrowOnError> => (options.client ?? client).post<PreviewRuleResponses, PreviewRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules/preview',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Rule
 */
export const getRule = <ThrowOnError extends boolean = false>(options: Options<GetRuleData, ThrowOnError>): RequestResult<GetRuleResponses, GetRuleErrors, ThrowOnError> => (options.client ?? client).get<GetRuleResponses, GetRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules/{rule_id}',
    ...options
});

/**
 * Update Rule
 */
export const updateRule = <ThrowOnError extends boolean = false>(options: Options<UpdateRuleData, ThrowOnError>): RequestResult<UpdateRuleResponses, UpdateRuleErrors, ThrowOnError> => (options.client ?? client).post<UpdateRuleResponses, UpdateRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules/{rule_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Move Rule
 *
 * Swap a rule with the one before (up) or after it (down): earlier rules are tried first.
 */
export const moveRule = <ThrowOnError extends boolean = false>(options: Options<MoveRuleData, ThrowOnError>): RequestResult<MoveRuleResponses, MoveRuleErrors, ThrowOnError> => (options.client ?? client).post<MoveRuleResponses, MoveRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules/{rule_id}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove Rule
 *
 * Stop using a rule. It is kept, so the hits it answered still name it.
 */
export const removeRule = <ThrowOnError extends boolean = false>(options: Options<RemoveRuleData, ThrowOnError>): RequestResult<RemoveRuleResponses, RemoveRuleErrors, ThrowOnError> => (options.client ?? client).post<RemoveRuleResponses, RemoveRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rules/{rule_id}/remove',
    ...options
});
