// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AddressActivity
 */
export type AddressActivity = {
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Country Code
     */
    country_code: string | null;
    /**
     * Requests
     */
    requests: number;
    /**
     * Distinct Paths
     */
    distinct_paths: number;
    /**
     * Login Attempts
     */
    login_attempts: number;
    /**
     * First Seen At
     */
    first_seen_at: string | null;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
};

/**
 * AuditAction
 */
export type AuditAction = 'login' | 'ban_created' | 'ban_revoked' | 'rule_created' | 'rule_changed' | 'rule_removed';

/**
 * AuditEntry
 */
export type AuditEntry = {
    /**
     * Id
     */
    id: number;
    /**
     * Logged At
     */
    logged_at: string;
    /**
     * Email
     */
    email: string;
    action: AuditAction;
    /**
     * Target Ip
     */
    target_ip: string | null;
    /**
     * Details
     */
    details: string;
};

/**
 * Ban
 *
 * An address's active ban, as the public sees it: when, never why or by whom.
 */
export type Ban = {
    /**
     * Since
     */
    since: string;
    /**
     * Until
     */
    until: string | null;
};

/**
 * BanRecord
 *
 * A ban in full: who made it and why, and whether and why it was revoked.
 */
export type BanRecord = {
    /**
     * Id
     */
    id: number;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Added
     */
    added: string;
    /**
     * Expires
     */
    expires: string | null;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Added By
     */
    added_by: string;
    /**
     * Revoked At
     */
    revoked_at: string | null;
    /**
     * Revoked By
     */
    revoked_by: string | null;
    /**
     * Revocation Reason
     */
    revocation_reason: string | null;
    /**
     * Active
     */
    active: boolean;
};

/**
 * CanaryOrigin
 *
 * Where a canary password was handed out: the leaked file, to whom, and when.
 */
export type CanaryOrigin = {
    /**
     * Path
     */
    path: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Issued At
     */
    issued_at: string;
};

/**
 * CategoryCount
 */
export type CategoryCount = {
    category: PathCategory;
    /**
     * Requests
     */
    requests: number;
    /**
     * Addresses
     */
    addresses: number;
};

/**
 * CountryCount
 */
export type CountryCount = {
    /**
     * Country Code
     */
    country_code: string | null;
    /**
     * Requests
     */
    requests: number;
    /**
     * Addresses
     */
    addresses: number;
};

/**
 * CredentialCount
 *
 * A username or password, and how often it was tried.
 */
export type CredentialCount = {
    /**
     * Value
     */
    value: string;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Addresses
     */
    addresses: number;
};

/**
 * DayActivity
 *
 * One UTC day's requests, hour by hour (24 numbers, from 00:00).
 */
export type DayActivity = {
    /**
     * Day
     */
    day: string;
    /**
     * Requests By Hour
     */
    requests_by_hour: Array<number>;
};

/**
 * Direction
 */
export type Direction = 'up' | 'down';

/**
 * EventPage
 *
 * One page of events, newest first.
 */
export type EventPage = {
    /**
     * Items
     */
    items: Array<HitEvent | LoginAttemptEvent | InstallAttemptEvent>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
    /**
     * Locations
     */
    locations: {
        [key: string]: IpLocation;
    };
};

/**
 * GoogleCallback
 *
 * What Google's redirect to the web app carried.
 */
export type GoogleCallback = {
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: string;
};

/**
 * GoogleLogin
 *
 * Where to send the admin to log in.
 */
export type GoogleLogin = {
    /**
     * Url
     */
    url: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HitDetail
 */
export type HitDetail = {
    /**
     * Kind
     */
    kind: 'hit';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Query
     */
    query: string | null;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * User Agent
     */
    user_agent: string | null;
    /**
     * Body Size
     */
    body_size: number | null;
    category: PathCategory;
    /**
     * Banned
     */
    banned: boolean;
    /**
     * Custom Response
     */
    custom_response: boolean;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body: string | null;
    /**
     * Body Truncated
     */
    body_truncated: boolean;
};

/**
 * HitEvent
 */
export type HitEvent = {
    /**
     * Kind
     */
    kind: 'hit';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Query
     */
    query: string | null;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * User Agent
     */
    user_agent: string | null;
    /**
     * Body Size
     */
    body_size: number | null;
    category: PathCategory;
    /**
     * Banned
     */
    banned: boolean;
    /**
     * Custom Response
     */
    custom_response: boolean;
    /**
     * Body Preview
     */
    body_preview: string | null;
    /**
     * Body Truncated
     */
    body_truncated: boolean;
};

/**
 * InstallAttemptEvent
 *
 * Someone finishing the decoy's "unfinished" WordPress install, to take the site over.
 * Nothing was installed: this is the account they chose.
 */
export type InstallAttemptEvent = {
    /**
     * Kind
     */
    kind: 'install_attempt';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Path
     */
    path: string;
    /**
     * Site Title
     */
    site_title: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Password Generated
     */
    password_generated: boolean;
};

/**
 * InstallOrigin
 *
 * The install that created the account a login used: which one, from where, and when.
 */
export type InstallOrigin = {
    /**
     * Id
     */
    id: number;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Attempted At
     */
    attempted_at: string;
};

/**
 * IpLocation
 *
 * Where an address is, as a geolocation database estimated it when the address was first
 * seen: never proof of where a sender is. A field is null when the database didn't know it.
 */
export type IpLocation = {
    /**
     * Country Code
     */
    country_code: string | null;
    /**
     * City
     */
    city: string | null;
    /**
     * Latitude
     */
    latitude: number | null;
    /**
     * Longitude
     */
    longitude: number | null;
    /**
     * Asn
     */
    asn: number | null;
    /**
     * As Organisation
     */
    as_organisation: string | null;
    /**
     * Source
     */
    source: string;
    /**
     * Located At
     */
    located_at: string;
};

/**
 * IpSummary
 *
 * What one IP address did, in numbers. The times are null when it sent no requests.
 */
export type IpSummary = {
    /**
     * Requests
     */
    requests: number;
    /**
     * Distinct Paths
     */
    distinct_paths: number;
    /**
     * Login Attempts
     */
    login_attempts: number;
    /**
     * Install Attempts
     */
    install_attempts: number;
    /**
     * Banned Requests
     */
    banned_requests: number;
    /**
     * First Seen At
     */
    first_seen_at: string | null;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
    location: IpLocation | null;
    ban: Ban | null;
};

/**
 * LoginAttemptEvent
 */
export type LoginAttemptEvent = {
    /**
     * Kind
     */
    kind: 'login_attempt';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Path
     */
    path: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Decoy Accepted
     */
    decoy_accepted: boolean;
    canary: CanaryOrigin | null;
    install: InstallOrigin | null;
};

/**
 * MapPlace
 *
 * A place located addresses are in (DB-IP gives a city's coordinates).
 */
export type MapPlace = {
    /**
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     */
    longitude: number;
    /**
     * City
     */
    city: string | null;
    /**
     * Country Code
     */
    country_code: string | null;
    /**
     * Requests
     */
    requests: number;
    /**
     * Addresses
     */
    addresses: number;
};

/**
 * Marker
 */
export type Marker = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * Me
 *
 * Who is logged in.
 */
export type Me = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * Move
 */
export type Move = {
    direction: Direction;
};

/**
 * NetworkCount
 */
export type NetworkCount = {
    /**
     * Asn
     */
    asn: number | null;
    /**
     * As Organisation
     */
    as_organisation: string | null;
    /**
     * Requests
     */
    requests: number;
    /**
     * Addresses
     */
    addresses: number;
};

/**
 * NewBan
 */
export type NewBan = {
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Expires
     */
    expires?: string | null;
};

/**
 * NewRule
 */
export type NewRule = {
    /**
     * Id
     */
    id: number;
};

/**
 * PathCategory
 */
export type PathCategory = 'homepage' | 'crawlers' | 'secrets' | 'backups' | 'debug' | 'exploits' | 'wordpress' | 'webshells' | 'logins' | 'apis' | 'other';

/**
 * PathCount
 */
export type PathCount = {
    /**
     * Path
     */
    path: string;
    category: PathCategory;
    /**
     * Requests
     */
    requests: number;
    /**
     * Addresses
     */
    addresses: number;
};

/**
 * Patterns
 */
export type Patterns = {
    /**
     * Computed At
     */
    computed_at: string;
    /**
     * Window Start
     */
    window_start: string;
    totals: Totals;
    /**
     * Categories
     */
    categories: Array<CategoryCount>;
    /**
     * Paths
     */
    paths: Array<PathCount>;
    /**
     * User Agents
     */
    user_agents: Array<UserAgentCount>;
    /**
     * Days
     */
    days: Array<DayActivity>;
    /**
     * Usernames
     */
    usernames: Array<CredentialCount>;
    /**
     * Passwords
     */
    passwords: Array<CredentialCount>;
    /**
     * Countries
     */
    countries: Array<CountryCount>;
    /**
     * Networks
     */
    networks: Array<NetworkCount>;
    /**
     * Busiest
     */
    busiest: Array<AddressActivity>;
    /**
     * Longest Seen
     */
    longest_seen: Array<AddressActivity>;
    /**
     * Toolkits
     */
    toolkits: Array<Toolkit>;
    /**
     * Places
     */
    places: Array<MapPlace>;
};

/**
 * Preview
 *
 * Whether the rule would answer that request, and what it would send (with a sample canary,
 * never a real one).
 */
export type Preview = {
    /**
     * Matches
     */
    matches: boolean;
    response: RenderedResponse;
};

/**
 * PreviewRequest
 *
 * A rule, and the request to try it on: as if `ip` had sent it.
 */
export type PreviewRequest = {
    rule: RuleForm;
    /**
     * Ip
     */
    ip: string;
    /**
     * Method
     */
    method?: string;
    /**
     * Path
     */
    path?: string;
};

/**
 * RenderedResponse
 *
 * What the decoy serves instead of its own page.
 */
export type RenderedResponse = {
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body: string;
    /**
     * Delay Ms
     */
    delay_ms: number;
};

/**
 * Revocation
 */
export type Revocation = {
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * RuleForm
 *
 * A rule as the admin writes it. Refused (422, with Liquid's message) unless every template
 * parses and renders for a sample visitor.
 */
export type RuleForm = {
    /**
     * Method
     */
    method?: string | null;
    /**
     * Path Pattern
     */
    path_pattern?: string | null;
    /**
     * Condition
     */
    condition?: string;
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Content Type
     */
    content_type?: string;
    /**
     * Headers
     */
    headers?: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body?: string;
    /**
     * Delay Ms
     */
    delay_ms?: number;
    /**
     * Expires
     */
    expires?: string | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * RuleRecord
 *
 * A saved rule, with how many hits it answered.
 */
export type RuleRecord = {
    /**
     * Method
     */
    method: string | null;
    /**
     * Path Pattern
     */
    path_pattern: string | null;
    /**
     * Condition
     */
    condition: string;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body: string;
    /**
     * Delay Ms
     */
    delay_ms: number;
    /**
     * Expires
     */
    expires: string | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Position
     */
    position: number;
    /**
     * Updated
     */
    updated: string;
    /**
     * Hits
     */
    hits: number;
};

/**
 * Session
 *
 * A new session: the token to send as a bearer token, and when it stops working.
 */
export type Session = {
    /**
     * Token
     */
    token: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * Takeover
 *
 * An install through the decoy's installer and every login into the account it created, from
 * whichever addresses: one takeover attempt, start to finish.
 */
export type Takeover = {
    install: InstallAttemptEvent;
    /**
     * Logins
     */
    logins: Array<LoginAttemptEvent>;
    /**
     * Login Count
     */
    login_count: number;
    /**
     * Locations
     */
    locations: {
        [key: string]: IpLocation;
    };
};

/**
 * Toolkit
 *
 * Addresses that each requested exactly the same set of paths: one tool, several machines.
 */
export type Toolkit = {
    /**
     * Paths
     */
    paths: number;
    /**
     * Address Count
     */
    address_count: number;
    /**
     * Addresses
     */
    addresses: Array<string>;
    /**
     * Example Paths
     */
    example_paths: Array<string>;
};

/**
 * Totals
 *
 * All time.
 */
export type Totals = {
    /**
     * Requests
     */
    requests: number;
    /**
     * Login Attempts
     */
    login_attempts: number;
    /**
     * Install Attempts
     */
    install_attempts: number;
    /**
     * Addresses
     */
    addresses: number;
    /**
     * Countries
     */
    countries: number;
    /**
     * Requests Last Day
     */
    requests_last_day: number;
    /**
     * First Seen At
     */
    first_seen_at: string | null;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
};

/**
 * UserAgentCount
 */
export type UserAgentCount = {
    /**
     * User Agent
     */
    user_agent: string | null;
    /**
     * Requests
     */
    requests: number;
    /**
     * Addresses
     */
    addresses: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListRecentEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Before
         */
        before?: string | null;
        /**
         * Take
         */
        take?: number;
    };
    url: '/exhibit/feed';
};

export type ListRecentEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRecentEventsError = ListRecentEventsErrors[keyof ListRecentEventsErrors];

export type ListRecentEventsResponses = {
    /**
     * Successful Response
     */
    200: EventPage;
};

export type ListRecentEventsResponse = ListRecentEventsResponses[keyof ListRecentEventsResponses];

export type GetIpEventsData = {
    body?: never;
    path: {
        /**
         * Ip Addr
         */
        ip_addr: string;
    };
    query?: {
        /**
         * Before
         */
        before?: string | null;
        /**
         * Take
         */
        take?: number;
    };
    url: '/exhibit/ip/{ip_addr}/activity';
};

export type GetIpEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIpEventsError = GetIpEventsErrors[keyof GetIpEventsErrors];

export type GetIpEventsResponses = {
    /**
     * Successful Response
     */
    200: EventPage;
};

export type GetIpEventsResponse = GetIpEventsResponses[keyof GetIpEventsResponses];

export type GetIpSummaryData = {
    body?: never;
    path: {
        /**
         * Ip Addr
         */
        ip_addr: string;
    };
    query?: never;
    url: '/exhibit/ip/{ip_addr}/summary';
};

export type GetIpSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIpSummaryError = GetIpSummaryErrors[keyof GetIpSummaryErrors];

export type GetIpSummaryResponses = {
    /**
     * Successful Response
     */
    200: IpSummary;
};

export type GetIpSummaryResponse = GetIpSummaryResponses[keyof GetIpSummaryResponses];

export type GetHitData = {
    body?: never;
    path: {
        /**
         * Hit Id
         */
        hit_id: number;
    };
    query?: never;
    url: '/exhibit/hits/{hit_id}';
};

export type GetHitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHitError = GetHitErrors[keyof GetHitErrors];

export type GetHitResponses = {
    /**
     * Successful Response
     */
    200: HitDetail;
};

export type GetHitResponse = GetHitResponses[keyof GetHitResponses];

export type GetTakeoverData = {
    body?: never;
    path: {
        /**
         * Install Id
         */
        install_id: number;
    };
    query?: never;
    url: '/exhibit/installs/{install_id}';
};

export type GetTakeoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTakeoverError = GetTakeoverErrors[keyof GetTakeoverErrors];

export type GetTakeoverResponses = {
    /**
     * Successful Response
     */
    200: Takeover;
};

export type GetTakeoverResponse = GetTakeoverResponses[keyof GetTakeoverResponses];

export type GetPatternsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/exhibit/patterns';
};

export type GetPatternsResponses = {
    /**
     * Successful Response
     */
    200: Patterns;
};

export type GetPatternsResponse = GetPatternsResponses[keyof GetPatternsResponses];

export type StartGoogleLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type StartGoogleLoginResponses = {
    /**
     * Successful Response
     */
    200: GoogleLogin;
};

export type StartGoogleLoginResponse = StartGoogleLoginResponses[keyof StartGoogleLoginResponses];

export type FinishGoogleLoginData = {
    body: GoogleCallback;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type FinishGoogleLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinishGoogleLoginError = FinishGoogleLoginErrors[keyof FinishGoogleLoginErrors];

export type FinishGoogleLoginResponses = {
    /**
     * Successful Response
     */
    200: Session;
};

export type FinishGoogleLoginResponse = FinishGoogleLoginResponses[keyof FinishGoogleLoginResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type LogOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogOutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogOutResponse = LogOutResponses[keyof LogOutResponses];

export type ListActiveBansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/bans';
};

export type ListActiveBansResponses = {
    /**
     * Response List Active Bans
     *
     * Successful Response
     */
    200: Array<BanRecord>;
};

export type ListActiveBansResponse = ListActiveBansResponses[keyof ListActiveBansResponses];

export type ListIpBansData = {
    body?: never;
    path: {
        /**
         * Ip Addr
         */
        ip_addr: string;
    };
    query?: never;
    url: '/admin/ip/{ip_addr}/bans';
};

export type ListIpBansErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListIpBansError = ListIpBansErrors[keyof ListIpBansErrors];

export type ListIpBansResponses = {
    /**
     * Response List Ip Bans
     *
     * Successful Response
     */
    200: Array<BanRecord>;
};

export type ListIpBansResponse = ListIpBansResponses[keyof ListIpBansResponses];

export type BanIpData = {
    body: NewBan;
    path: {
        /**
         * Ip Addr
         */
        ip_addr: string;
    };
    query?: never;
    url: '/admin/ip/{ip_addr}/bans';
};

export type BanIpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BanIpError = BanIpErrors[keyof BanIpErrors];

export type BanIpResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type BanIpResponse = BanIpResponses[keyof BanIpResponses];

export type RevokeBanData = {
    body: Revocation;
    path: {
        /**
         * Ban Id
         */
        ban_id: number;
    };
    query?: never;
    url: '/admin/bans/{ban_id}/revoke';
};

export type RevokeBanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeBanError = RevokeBanErrors[keyof RevokeBanErrors];

export type RevokeBanResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeBanResponse = RevokeBanResponses[keyof RevokeBanResponses];

export type ListAuditLogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/audit';
};

export type ListAuditLogResponses = {
    /**
     * Response List Audit Log
     *
     * Successful Response
     */
    200: Array<AuditEntry>;
};

export type ListAuditLogResponse = ListAuditLogResponses[keyof ListAuditLogResponses];

export type ListRulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/rules';
};

export type ListRulesResponses = {
    /**
     * Response List Rules
     *
     * Successful Response
     */
    200: Array<RuleRecord>;
};

export type ListRulesResponse = ListRulesResponses[keyof ListRulesResponses];

export type CreateRuleData = {
    body: RuleForm;
    path?: never;
    query?: never;
    url: '/admin/rules';
};

export type CreateRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRuleError = CreateRuleErrors[keyof CreateRuleErrors];

export type CreateRuleResponses = {
    /**
     * Successful Response
     */
    200: NewRule;
};

export type CreateRuleResponse = CreateRuleResponses[keyof CreateRuleResponses];

export type ListRuleMarkersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/rules/markers';
};

export type ListRuleMarkersResponses = {
    /**
     * Response List Rule Markers
     *
     * Successful Response
     */
    200: Array<Marker>;
};

export type ListRuleMarkersResponse = ListRuleMarkersResponses[keyof ListRuleMarkersResponses];

export type PreviewRuleData = {
    body: PreviewRequest;
    path?: never;
    query?: never;
    url: '/admin/rules/preview';
};

export type PreviewRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewRuleError = PreviewRuleErrors[keyof PreviewRuleErrors];

export type PreviewRuleResponses = {
    /**
     * Successful Response
     */
    200: Preview;
};

export type PreviewRuleResponse = PreviewRuleResponses[keyof PreviewRuleResponses];

export type GetRuleData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: number;
    };
    query?: never;
    url: '/admin/rules/{rule_id}';
};

export type GetRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuleError = GetRuleErrors[keyof GetRuleErrors];

export type GetRuleResponses = {
    /**
     * Successful Response
     */
    200: RuleRecord;
};

export type GetRuleResponse = GetRuleResponses[keyof GetRuleResponses];

export type UpdateRuleData = {
    body: RuleForm;
    path: {
        /**
         * Rule Id
         */
        rule_id: number;
    };
    query?: never;
    url: '/admin/rules/{rule_id}';
};

export type UpdateRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRuleError = UpdateRuleErrors[keyof UpdateRuleErrors];

export type UpdateRuleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateRuleResponse = UpdateRuleResponses[keyof UpdateRuleResponses];

export type MoveRuleData = {
    body: Move;
    path: {
        /**
         * Rule Id
         */
        rule_id: number;
    };
    query?: never;
    url: '/admin/rules/{rule_id}/move';
};

export type MoveRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoveRuleError = MoveRuleErrors[keyof MoveRuleErrors];

export type MoveRuleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MoveRuleResponse = MoveRuleResponses[keyof MoveRuleResponses];

export type RemoveRuleData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: number;
    };
    query?: never;
    url: '/admin/rules/{rule_id}/remove';
};

export type RemoveRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveRuleError = RemoveRuleErrors[keyof RemoveRuleErrors];

export type RemoveRuleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveRuleResponse = RemoveRuleResponses[keyof RemoveRuleResponses];
