// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DecoyPasswordAttemptEvent
 */
export type DecoyPasswordAttemptEvent = {
    /**
     * Kind
     */
    kind: 'decoy_password_attempt';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Decoy Slug
     */
    decoy_slug: string;
    /**
     * Decoy Accepted
     */
    decoy_accepted: boolean;
};

/**
 * DecoyType
 */
export type DecoyType = 'text' | 'binary' | 'trap';

/**
 * DecoyViewEvent
 */
export type DecoyViewEvent = {
    /**
     * Kind
     */
    kind: 'decoy_view';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Decoy Slug
     */
    decoy_slug: string;
    decoy_type: DecoyType;
};

/**
 * EventPage
 *
 * One page of events, newest first.
 */
export type EventPage = {
    /**
     * Items
     */
    items: Array<HitEvent | LoginAttemptEvent | DecoyViewEvent | DecoyPasswordAttemptEvent>;
    /**
     * Has Next
     */
    has_next: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HitDetail
 */
export type HitDetail = {
    /**
     * Kind
     */
    kind: 'hit';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Query
     */
    query: string | null;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * User Agent
     */
    user_agent: string | null;
    /**
     * Body Size
     */
    body_size: number | null;
    /**
     * Headers
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Body
     */
    body: string | null;
    /**
     * Body Truncated
     */
    body_truncated: boolean;
};

/**
 * HitEvent
 */
export type HitEvent = {
    /**
     * Kind
     */
    kind: 'hit';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Query
     */
    query: string | null;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * User Agent
     */
    user_agent: string | null;
    /**
     * Body Size
     */
    body_size: number | null;
    /**
     * Body Preview
     */
    body_preview: string | null;
    /**
     * Body Truncated
     */
    body_truncated: boolean;
};

/**
 * IpSummary
 *
 * What one IP address did, in numbers. The times are null when it sent no requests.
 */
export type IpSummary = {
    /**
     * Requests
     */
    requests: number;
    /**
     * Distinct Paths
     */
    distinct_paths: number;
    /**
     * Login Attempts
     */
    login_attempts: number;
    /**
     * First Seen At
     */
    first_seen_at: string | null;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
};

/**
 * LoginAttemptEvent
 */
export type LoginAttemptEvent = {
    /**
     * Kind
     */
    kind: 'login_attempt';
    /**
     * Id
     */
    id: number;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Ip Address
     */
    ip_address: string;
    /**
     * Path
     */
    path: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Decoy Accepted
     */
    decoy_accepted: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListRecentEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Take
         */
        take?: number;
    };
    url: '/exhibit/feed';
};

export type ListRecentEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRecentEventsError = ListRecentEventsErrors[keyof ListRecentEventsErrors];

export type ListRecentEventsResponses = {
    /**
     * Successful Response
     */
    200: EventPage;
};

export type ListRecentEventsResponse = ListRecentEventsResponses[keyof ListRecentEventsResponses];

export type GetIpEventsData = {
    body?: never;
    path: {
        /**
         * Ip Addr
         */
        ip_addr: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Take
         */
        take?: number;
    };
    url: '/exhibit/ip/{ip_addr}/activity';
};

export type GetIpEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIpEventsError = GetIpEventsErrors[keyof GetIpEventsErrors];

export type GetIpEventsResponses = {
    /**
     * Successful Response
     */
    200: EventPage;
};

export type GetIpEventsResponse = GetIpEventsResponses[keyof GetIpEventsResponses];

export type GetIpSummaryData = {
    body?: never;
    path: {
        /**
         * Ip Addr
         */
        ip_addr: string;
    };
    query?: never;
    url: '/exhibit/ip/{ip_addr}/summary';
};

export type GetIpSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIpSummaryError = GetIpSummaryErrors[keyof GetIpSummaryErrors];

export type GetIpSummaryResponses = {
    /**
     * Successful Response
     */
    200: IpSummary;
};

export type GetIpSummaryResponse = GetIpSummaryResponses[keyof GetIpSummaryResponses];

export type GetHitData = {
    body?: never;
    path: {
        /**
         * Hit Id
         */
        hit_id: number;
    };
    query?: never;
    url: '/exhibit/hits/{hit_id}';
};

export type GetHitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHitError = GetHitErrors[keyof GetHitErrors];

export type GetHitResponses = {
    /**
     * Successful Response
     */
    200: HitDetail;
};

export type GetHitResponse = GetHitResponses[keyof GetHitResponses];
