// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListIpActivityRow
 */
export type ListIpActivityRow = {
    /**
     * Event At
     */
    event_at: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Target Id
     */
    target_id: number;
    /**
     * Target Slug
     */
    target_slug: string;
    /**
     * Details
     */
    details: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type IpGetIpActivityData = {
    body?: never;
    path: {
        /**
         * Ip Addr
         */
        ip_addr: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Take
         */
        take?: number;
    };
    url: '/exhibit/ip/{ip_addr}/activity';
};

export type IpGetIpActivityErrors = {
    /**
     * Not Found
     */
    404: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: Message;
};

export type IpGetIpActivityError = IpGetIpActivityErrors[keyof IpGetIpActivityErrors];

export type IpGetIpActivityResponses = {
    /**
     * Response Ip.Get Ip Activity
     *
     * Successful Response
     */
    200: Array<ListIpActivityRow>;
};

export type IpGetIpActivityResponse = IpGetIpActivityResponses[keyof IpGetIpActivityResponses];
