[project]
name = "attenborough"
version = "0.1.0"
description = "The backend for Attenborough"
readme = "README.md"
authors = [
    { name = "tristanbatchler", email = "info@tbat.me" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[pool]>=3.3.5",
]

[project.scripts]
api = "attenborough:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "ruff>=0.16.4",
    "sqlc-bin>=1.31.1.post1",
]

[tool.ruff]
exclude = [
    "src/attenborough/db/query.py",
    "src/attenborough/db/models.py",
]

[tool.basedpyright]
ignore = [
    "src/attenborough/db/query.py",
    "src/attenborough/db/models.py",
]
typeCheckingMode = "strict"


[tool.fastapi]
entrypoint = "attenborough.main:app"
